### ISSUE TITLE
(Exactly once delivery) BatchError: Failed to "modifyAckDeadline" Reason: 3 INVALID_ARGUMENT.

### ISSUE THREAD

**Issue by JaegarSarauer** [googleapis/nodejs-pubsub#1547] opened 2022-05-04 00:29 UTC
1) Is this a client library issue or a product issue?
Client Library Issue.

2) Did someone already solve this?
  - [x] Search the issues already opened: https://github.com/googleapis/nodejs-pubsub/issues
  - [x] Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - [x] Search or ask on StackOverflow (engineers monitor these tags): http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

3) Do you have a support contract?
No.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: `Mac OS Monterey 12.3.1 (M1)`
  - Node.js version: `v14.19.1`
  - npm version: `6.14.16`
  - `@google-cloud/pubsub` version: `^2.19.0`

#### Steps to reproduce

  1. Create a Topic and Subscription for a project in the [PubSub console](https://console.cloud.google.com/cloudpubsub/topic/list).
      a) Assign the google API scope: `gmail-api-push@system.gserviceaccount.com` to the topic and subscription.
      b) Enable "Exactly once delivery" for the subscription. 
  2. Create a project which watches a mailbox for unread messages and gets the subscription just created: 
  ```
  const pubsub = new PubSub({ projectId: 'example-project' });
  const sub = await pubsub.subscription('example-project-sub');

  sub.on('error', async (error) => {
    console.info('Pubsub subscribe error: ', error);
  });

  sub.on('message', async (message) => {
    try {
      message.ack();
    } catch (err) {
      console.info(err);
    }
  });

  await gmail.users.watch({
      userId: 'me',
      requestBody: {
        labelIds: ['UNREAD'],
        topicName: `projects/example-project/topics/example-project-topic`,
      },
    })
```
(Authentication Code):
```
  const { google } = require('googleapis');

  const JWT = google.auth.JWT;
  const auth = new JWT({
    keyFile: 'credentials-service.json',
    scopes: ['https://www.googleapis.com/auth/gmail.readonly', 'https://mail.google.com/'],
    subject: 'email@gmail.com',
  });

  await auth.authorize();

  const gmail = google.gmail({
    auth,
    version: 'v1',
  });
```

 4. Run the project concurrently with at least 2 instances.
 5. Send 10 unique emails to the email matched to the topic in fast succession.
 6. Witness the error appear:
 ```
BatchError: Failed to "modifyAckDeadline" for 1 message(s). Reason: 3 INVALID_ARGUMENT: Some acknowledgement ids in the request were invalid. This could be because the acknowledgement ids have expired or the acknowledgement ids were malformed.
    at ./example-project/node_modules/@google-cloud/pubsub/src/message-queues.ts:258:15
    at async Promise.all (index 0)
    at async ModAckQueue._sendBatch (./example-project/node_modules/@google-cloud/pubsub/src/message-queues.ts:262:5)
    at async ModAckQueue.flush (./example-project/node_modules/@google-cloud/pubsub/src/message-queues.ts:142:7) {
  ackIds: [
    'BhYsXUZIUTcZCGhRDk9eIz81IChFEgADZ3kiHkYfYmhcXHUHUAUZei5hcmNbRwkIR1Z0X3MrFZ22qtYxUa3P8PXZdUh6FwULRVp_WV8ZC2tfX3YPUyWguYL5j-KZJBs-faaUqfgtLZu7y682Zi09WhJLLD5-NTZFQV5AEkw-A0RJUytDCypYEU4EISE-MD5FU0RQ'
  ],
  code: 3,
  details: 'Some acknowledgement ids in the request were invalid. This could be because the acknowledgement ids have expired or the acknowledgement ids were malformed.',
  metadata: Metadata {
    internalRepr: Map(2) {
      'google.rpc.errorinfo-bin' => "EXACTLY_ONCE_ACKID_FAILUREpubsub.googleapis.com�
�BhYsXUZIUTcZCGhRDk9eIz81IChFEgADZ3kiHkYfYmhcXHUHUAUZei5iI2gPG1AIRlp0X3MrFcCaqtYxUa3P8PXZdUh6FwULRVp9X10TDWlVX3IGVCWguYL5j-KZJBs-ffu4qfgtLYDZlqg2Zi09WhJLLD5-NTZFQV5AEkw-A0RJUytDCypYEU4EISE-MD5FU0RQ PERMANENT_FAILURE_INVALID_ACK_ID",
      'grpc-status-details-bin' => "�Some acknowledgement ids in the request were invalid. This could be because the acknowledgement ids have expired or the acknowledgement ids were malformed.�
(type.googleapis.com/google.rpc.ErrorInfo�
EXACTLY_ONCE_ACKID_FAILUREpubsub.googleapis.com�
�BhYsXUZIUTcZCGhRDk9eIz81IChFEgADZ3kiHkYfYmhcXHUHUAUZei5iI2gPG1AIRlp0X3MrFcCaqtYxUa3P8PXZdUh6FwULRVp9X10TDWlVX3IGVCWguYL5j-KZJBs-ffu4qfgtLYDZlqg2Zi09WhJLLD5-NTZFQV5AEkw-A0RJUytDCypYEU4EISE-MD5FU0RQ PERMANENT_FAILURE_INVALID_ACK_ID"
    },
    options: {}
  }
}
```

#### Additional Details:
 - There is no online record of this extended error log: `"Some acknowledgement ids in the request were invalid. This could be because the acknowledgement ids have expired or the acknowledgement ids were malformed."`.
     - Except for [this PR](https://github.com/googleapis/google-cloud-dotnet/pull/8287) in the pubsub .net repo.

**Comment by JaegarSarauer** [comment] 2022-05-04 01:02
Closing for now as I am able to remove the error by removing more of the code from my project.
At first I had thought the problem stemmed from the `ack()` call on the subscriber message,  but it may be due to how I am handling history and messages further into the project.

**Comment by JaegarSarauer** [comment] 2022-05-04 19:34
I have reopened as I was able to verify the bug is reproducible with the above code.

**Comment by feywind** [comment] 2022-05-05 21:04
@JaegarSarauer Thanks for the report and all the info. The Node library for Pub/Sub doesn't currently support Exact Once, but it's a feature that's currently in progress.

**Comment by JaegarSarauer** [comment] 2022-05-05 22:00
No problem, thanks for the reply. 

For anyone who may come across this problem and need a solution, I ended up using a [distributed lock (using redis)](https://redis.io/docs/reference/patterns/distributed-locks/).

With dist locks, I was able to lock the resource I was using on one of my program instances, so I didn't mind getting excess messages from Pub/Sub.

**Comment by feywind** [comment] 2022-08-16 19:16
@JaegarSarauer Ah, thanks for the follow-up (sorry for my slow follow-up follow-up). I'm hoping we'll have proper exactly-once support in Node soon but it's good you found a solution.

**Comment by shoxsz** [comment] 2022-09-07 17:57
I don't get it, why should the nodejs library have support for it? shouldn't it be a behaviour from the pubsub backend side?

**Comment by feywind** [comment] 2022-09-07 18:10
@shoxsz It is, but it requires a fair amount of client library support to work gracefully and correctly. Specifically, we need to allow users to get a response from calling ack() on a message, to see if they actually claimed it or not.

**Comment by shoxsz** [comment] 2022-09-07 18:16
Thanks for the quick reply, can you tell me if this have been solved in the current version 3.1.0?

**Comment by feywind** [comment] 2022-09-07 18:23
@shoxsz It hasn't been merged, but it's in the later stages of development right now, fingers crossed that it won't be too long.

**Comment by shoxsz** [comment] 2022-09-07 18:25
Waiting for it, thanks for the help.

**Comment by Bielykh-Artem** [comment] 2022-10-05 12:18
3.2.0 issue still actual
error: OTHER : 3 INVALID_ARGUMENT: Some acknowledgement ids in the request were invalid. This could be because the acknowledgement ids have expired or the acknowledgement ids were malformed.
    at /Users/capgemini/projects/medable/screenshot-service/node_modules/@google-cloud/pubsub/src/message-queues.ts:419:21
    at Array.forEach (<anonymous>)
    at ModAckQueue.handleAckFailures (/Users/capgemini/projects/medable/screenshot-service/node_modules/@google-cloud/pubsub/src/message-queues.ts:418:12)
    at /Users/capgemini/projects/medable/screenshot-service/node_modules/@google-cloud/pubsub/src/message-queues.ts:563:33
    at async Promise.all (index 0)
    at async ModAckQueue._sendBatch (/Users/capgemini/projects/medable/screenshot-service/node_modules/@google-cloud/pubsub/src/message-queues.ts:574:45)
    at async ModAckQueue.flush (/Users/capgemini/projects/medable/screenshot-service/node_modules/@google-cloud/pubsub/src/message-queues.ts:269:23) {
  errorCode: 'OTHER'

**Comment by mkorpar** [comment] 2022-10-07 12:20
Have been experiencing the same issue. Furthermore it is crashing my app. Is there some kind of missed error propagation missing and is thrown "into the void"? I've made everything according to examples available on google docs pages.

**Comment by modestaspruckus** [comment] 2022-10-13 09:12
Same issue appears after upgrade to 3.2

**Comment by feywind** [comment] 2022-10-13 17:21
I'll reopen this.

**Comment by Bielykh-Artem** [comment] 2022-10-19 21:14
@feywind Hello! Could you help - how can I intercept and suppress this error so that it does not lead to restarting pods in Kubernetes. if i put a call of message.ack(); inside try/catch doesn't help. subscription.on("error", () => {}) doesn't catch this error either

**Comment by Bielykh-Artem** [comment] 2022-10-19 22:22
In my case, I think this error occurs because ackDeadline > 600, what happens if I use modAck(0) instead of ack() ?

**Comment by Bielykh-Artem** [comment] 2022-10-20 15:17
@mkorpar Hello! Could you please share for me your solution

**Comment by bonzzy** [comment] 2022-11-14 10:41
Is there any progress made on this part? 
I get the same error when using `exactly once` delivery and NodeJs. 
`ackError: INVALID : 3 INVALID_ARGUMENT: Some acknowledgement ids in the request were invalid`

Is the solution for now not to use `exactly once` delivery with NodeJs?

**Comment by udnes99** [comment] 2022-11-24 09:39
Occurred for us today as well (NOT using exactly-once delivery), leading to pods in K8s having to be restarted. This persisted for a while until it seemingly resolved on its own. Still detrimental to the availability of our services. 
```
 "AckError: INVALID : 3 INVALID_ARGUMENT: Some acknowledgement ids in the request were invalid. This could be because the acknowledgement ids have expired or the acknowledgement ids were malformed.
    at /app/node_modules/@google-cloud/pubsub/build/src/message-queues.js:330:29
    at Array.forEach (<anonymous>)
    at ModAckQueue.handleAckFailures (/app/node_modules/@google-cloud/pubsub/build/src/message-queues.js:328:18)
    at /app/node_modules/@google-cloud/pubsub/build/src/message-queues.js:470:43
    at async Promise.all (index 1)
    at async ModAckQueue._sendBatch (/app/node_modules/@google-cloud/pubsub/build/src/message-queues.js:476:31)
    at async ModAckQueue.flush (/app/node_modules/@google-cloud/pubsub/build/src/message-queues.js:195:29) {"
```

**Comment by Ganitzsh** [comment] 2022-11-25 12:39
Bumped into the same issue yesterday using the latest version 3.2.1. Downgrading to 3.2.0 reduced the amount of errors, and acknowledging messages works fine. So for now I have catch all on `uncaughtException` that logs the error when this particular one occurs, otherwise I just exit the process. This is a workaround and it's not ideal, hoping for a fix soon

**Comment by youb93** [comment] 2022-12-09 13:44
Hello, 
Same issue over there, is there any new about it ?

**Comment by Ori-b** [comment] 2022-12-14 13:23
Any news? getting the same issues:
1. 'uncaughtException' instead of a properly propagated exception (that can be caught on.('error')
2. Exactly once delivery - i am holding a message unacked and still get re-deliveries of un-acked messages within each hour....what is the client library logic regarding that duration? (it seems that the ackDeadline has no effect whether it is 10 seconds, or 600 seconds) see images below.
3. Is the Exactly Once delivery could be said to be operational in any sense? 
![image](https://user-images.githubusercontent.com/105278211/207606538-204bbf61-3221-4d1a-8f49-5400925ce050.png)
![image](https://user-images.githubusercontent.com/105278211/207606620-f4884f00-b189-4df7-ae2e-ac1eab75c6c8.png)

**Comment by garymathews** [comment] 2022-12-25 02:01
I'm also running into this issue.

From what I've found it's caused by this deferred promise.
https://github.com/googleapis/nodejs-pubsub/blob/main/src/message-queues.ts#L191
```JS
...
const responsePromise = defer<void>();

// TC1. Doing this still causes the 'unhandledException'.
responsePromise.promise.catch(() => {});

// TC2. Doing this prevents the 'unhandledException'. Note the existing promise in 'responsePromise' is being updated.
responsePromise.promise = responsePromise.promise.catch(() => {});

this._requests.push({
...
```

So this `.catch` handler is being ignored.
https://github.com/googleapis/nodejs-pubsub/blob/main/src/subscriber.ts#L531-L533

For the time being, my workaround is to use an _uncaughtException_ handler.

**Closed** 2023-01-23 20:52 UTC
Labels: priority: p2, type: bug, api: pubsub

**Comment by modestaspruckus** [comment] 2023-01-25 17:18
Hey,
Issue still persists on 3.3.0 version

```js
INVALID : 3 INVALID_ARGUMENT: Some acknowledgement ids in the request were invalid. This could be because the acknowledgement ids have expired or the acknowledgement ids were malformed.
/home/builder/backend/releases/543/node_modules/@google-cloud/pubsub/src/message-queues.ts in <anonymous> at line 419:21
/home/builder/backend/releases/543/node_modules/@google-cloud/pubsub/src/message-queues.ts in Array.forEach
/home/builder/backend/releases/543/node_modules/@google-cloud/pubsub/src/message-queues.ts in ModAckQueue.handleAckFailures at line 418:12
/home/builder/backend/releases/543/node_modules/@google-cloud/pubsub/src/message-queues.ts in <anonymous> at line 563:33
/home/builder/backend/releases/543/node_modules/@google-cloud/pubsub/src/message-queues.ts in Promise.all
/home/builder/backend/releases/543/node_modules/@google-cloud/pubsub/src/message-queues.ts in ModAckQueue._sendBatch at line 574:45
/home/builder/backend/releases/543/node_modules/@google-cloud/pubsub/src/message-queues.ts in ModAckQueue.flush at line 269:23
```

**Comment by Bielykh-Artem** [comment] 2023-02-22 11:49
Actual: INVALID : 3 INVALID_ARGUMENT: Some acknowledgement ids in the request were invalid. This could be because the acknowledgement ids have expired or the acknowledgement ids were malformed.

**Comment by fabioszymanski** [comment] 2023-02-28 23:08
Hey guys, is there any news in this issue? Any workaround? 
I'm facing the same here when consuming a message from a subscription with  exactly-once delivery activeted, this is intermittent, can't find the root cause exactly.

`UnhandledPromiseRejectionWarning: Error: INVALID : 3 INVALID_ARGUMENT: Some acknowledgement ids in the request were invalid`

the whole error is:
`(node:1) UnhandledPromiseRejectionWarning: Error: INVALID : 3 INVALID_ARGUMENT: Some acknowledgement ids in the request were invalid. 
This could be because the acknowledgement ids have expired or the acknowledgement ids were malformed. 
at /app/node_modules/@google-cloud/pubsub/build/src/message-queues.js:330:29 
at Array.forEach (<anonymous>) 
at AckQueue.handleAckFailures (/app/node_modules/@google-cloud/pubsub/build/src/message-queues.js:328:18) 
at AckQueue._sendBatch (/app/node_modules/@google-cloud/pubsub/build/src/message-queues.js:401:42) 
at async AckQueue.flush (/app/node_modules/@google-cloud/pubsub/build/src/message-queues.js:195:29)`

**Comment by feywind** [comment] 2023-03-01 20:17
Those look like errors coming from the Pub/Sub service itself, and there's not a lot we can do from the client library end outside of entering a support ticket (to be able to look at the backend to try to match up times and errors). :(

If these are resulting in an error when exactly once delivery is disabled, or an unhandled rejection that user code can't catch, that's something I can look at library-side. Without EOD enabled, this error shouldn't occur at all. And if you've got a try/catch around the ack() call, it shouldn't turn into an unhandled rejection.

**Comment by anthony-langford** [comment] 2023-04-24 19:02
Experiencing the same error here with other packages as well (e.g. `@algoan/pub-sub`).

**Comment by patrykcieszkowski** [comment] 2024-05-01 08:33
The issue is still present.

- the event `ackDeadline` is set to `120`
- the event handler took `2` seconds to complete the job (artificially extended)
- the event handler sends `ackWithResponse` - if the job was successful, and within the error handler
- package version: `^4.1.1`

the error:
```
OTHER : 3 INVALID_ARGUMENT: Some acknowledgement ids in the request were invalid. This could be because the acknowledgement ids have expired or the acknowledgement ids were malformed.
```

**Comment by Luisgustavom1** [comment] 2024-09-03 14:52
Some update? 

this error still persists
