### ISSUE TITLE
when using with PM2, not providing a projectID will cause the app to take 100% CPU without throwing any error

### ISSUE THREAD

**Issue by zerubeus** [googleapis/nodejs-pubsub#438] opened 2019-01-22 23:18 UTC
#### Environment details

  - OS: Mac OS 10.14
  - Node.js version: 10.15
  - npm version:
  - `@google-cloud/pubsub` version: 0.22.2

#### Steps to reproduce

  1. when using with PM2, not providing a projectID will cause the app to take 100% CPU without throwing any error

suspect code : 

https://github.com/googleapis/nodejs-pubsub/blob/master/src/index.ts#L744
https://github.com/googleapis/nodejs-pubsub/blob/master/src/index.ts#L745

**Comment by callmehiphop** [comment] 2019-01-23 18:53
Hi @zerubeus and thanks for the issue report! I think this is actually a duplicate of #288. `0.23.0` was released recently and I was wondering if you'd be willing to test against that version to see if this issue persists. Either way, I'm going to close this issue, but hopefully we'll come to a resolution in #288 soon. Thanks!

**Closed by callmehiphop** 2019-01-23 18:53 UTC
Labels: triage me

**Comment by callmehiphop** [comment] 2019-01-28 18:15
@zerubeus I just made a [release](https://github.com/googleapis/nodejs-pubsub/pull/452) (`0.24.0`) that should resolve the issue you're seeing. If you continue to encounter this issue, please let us know! Thanks again for the report!

**Comment by zerubeus** [comment] 2019-02-06 16:52
@callmehiphop thank you
