### ISSUE TITLE
Sample tests are flaky

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-pubsub#884] opened 2020-02-10 17:41 UTC
Looking at https://github.com/googleapis/nodejs-pubsub/pull/882, there's no reason the sample tests should be failing there. 

Results are here:
https://source.cloud.google.com/results/invocations/c478b728-cd2b-4a0f-a3a5-545b2b668db1/targets/cloud-devrel%2Fclient-libraries%2Fnodejs%2Fpresubmit%2Fgoogleapis%2Fnodejs-pubsub%2Fnode10%2Fsamples-test/log

**Comment by feywind** [comment] 2020-02-10 17:50
To be fair, this deadline exceeded thing is something we've been hearing about outside of sample tests, so this might just be the sample tests working as intended.

**Comment by JustinBeckwith** [comment] 2020-02-10 17:53
_nods_ I hear ya.  May not be anything we're doing wrong in the code, but we can't be flakin.  I'm fine with tactical retries if that's what we need here.

**Comment by feywind** [comment] 2020-02-10 17:56
Oh I agree, I just think it's potentially nice that the tests are catching problems rather than just being flaky :)

**Comment by feywind** [comment] 2020-02-11 21:42
I think this may also go on the flake list (though not strictly about samples, I'm okay with this issue being a bit expansive). https://github.com/googleapis/nodejs-pubsub/pull/880/checks?check_run_id=439299785

**Comment by feywind** [comment] 2020-02-27 20:43
Combining this in here to look at, at the same time. https://github.com/googleapis/nodejs-pubsub/issues/900

**Comment by JustinBeckwith** [comment] 2020-02-27 21:05
Oops - apologies, forgot I had opened this one!

**Comment by feywind** [comment] 2020-02-27 21:09
Hah, no worries. :) It technically is a separate issue to look into, though I think fixing one will probably fix the other.

**Comment by feywind** [comment] 2020-03-04 19:48
https://github.com/googleapis/nodejs-pubsub/pull/880/checks?check_run_id=485759235

**Comment by feywind** [comment] 2020-03-25 23:32
https://source.cloud.google.com/results/invocations/0b75c074-4b85-4193-bbc0-3a6f10dc8af9/targets/cloud-devrel%2Fclient-libraries%2Fnodejs%2Fpresubmit%2Fgoogleapis%2Fnodejs-pubsub%2Fnode10%2Fsamples-test/log

(part of https://github.com/googleapis/nodejs-pubsub/pull/916)

**Comment by feywind** [comment] 2020-05-05 17:45
There haven't been any sample test flakes for a while, and we have buildcop coming online for finding them individually, anyway. I'm going to go ahead and close this.

**Closed by feywind** 2020-05-05 17:45 UTC
Labels: type: cleanup
