### ISSUE TITLE
`nackWithResponse()` is successful, but the stream is stopped.

### ISSUE THREAD

**Issue by daffron** [googleapis/nodejs-pubsub#1708] opened 2023-04-13 16:27 UTC
#### Environment details

  - OS: Ubuntu 20.04
  - Node.js version: 18
  - npm version: 8.11
  - `@google-cloud/pubsub` version: 3.4.1

#### Steps to reproduce

  1. Create a topic, with a subscription with a retry policy and dead letter topic. Enable exactly once delivery
  2. Create the event listener, set flow control max messages to 1 for clarity. On each message, call `nackWithResponse()`
  3. Publish a number of messages to the topic.
  4. Observe the first message is `nacked`, the result is `SUCCESS`. However the stream stops, and no further messages are processed. 
  
It looks like it nacks successfully, as on process restart messages come through with higher delivery attempt counts, its the calling of `nackWithResponse` that seems to stop the stream.

- Calling `nack()` works perfectly still, will use as a work around for now.
- Changing the line to `ackWithResponse()` works and does not stop the stream, meaning the implementation must be fine also.  

Thanks!

**Comment by feywind** [comment] 2023-04-17 15:15
@daffron Thanks for the report. The nack calls are more or less wrappers for modAck(0), so that's strange behaviour. I don't guess you're using ordering keys?

**Comment by daffron** [comment] 2023-04-18 04:15
Hey @feywind ,

Not using any ordering keys. Only DL topic, and exactly once delivery

**Comment by yfyau** [comment] 2023-09-08 19:59
Related to https://github.com/googleapis/nodejs-pubsub/issues/1679#issuecomment-1440414759
Updating Nodejs to >=16.20.0 or >=18.15.0 should resolve the issue.

Since this is not a bug of the pubsub package, it can be closed.

**Comment by feywind** [comment] 2023-09-26 16:44
@daffron Do you concur that this was related to that Node bug linked above by yfyau? If so, we can go ahead and close it.

**Comment by feywind** [comment] 2023-10-16 19:33
I'm going to assume this was solved by the linked issue above. Please comment if not.

**Closed by feywind** 2023-10-16 19:33 UTC
Labels: priority: p2, type: bug, api: pubsub
