### ISSUE TITLE
Memory Leak on Subscription (Windows)

### ISSUE THREAD

**Issue by nirbenda** [googleapis/nodejs-pubsub#500] opened 2019-02-27 09:27 UTC
Hello,

I am experiencing what seems to be a memory leak.
At first the NodeJS process memory is ~40MB and after about 5-10 minutes (of continiuosly receiving messages every two seconds and acking them) it rapidly grows from 40MB to 1.6GB in term of seconds, and after a few minutes Node crashes with OOM because it excceeded the maximum capacity allowed for memory allocation.
Inspecting the allocations points to the promisify and JSBufferArray allocations. 
I might be doing something wrong, but this code was taken from the examples (only that the listener timeout was removed).

Help would me much appreciated.

Thanks,
Nir

#### Environment details

  - OS: Windows 10
  - Node.js version: v8.10.0
  - npm version: 6.8.0
  - `@google-cloud/pubsub` version: 0.25.0

#### Steps to reproduce

  1. Publish to a topic once in two seconds using external service ( I use python for this for example )
  2. Run a subscription listener service, such as this for NodeJS:
```

var http = require('http');
async function listenForErrors(subscriptionName) {
  const {PubSub} = require('@google-cloud/pubsub');
  const pubsub = new PubSub();
  const subscription = pubsub.subscription(subscriptionName);

  const messageHandler = function(message) {
    console.log('got a message ');
    message.ack();
  };

  subscription.on(`message`, messageHandler);
}
listenForErrors("my-sub")
 
//create a server object:
http.createServer(function (req, res) {
  res.write('Hello World!'); //write a response to the client
  res.end(); //end the response
}).listen(8080); //the server object listens on port 8080 


```

**Comment by callmehiphop** [comment] 2019-02-27 09:39
Hi @nirbenda, do you know approximately how many messages you have waiting to be processed? If you're only getting 1 every 2 seconds that would mean over the course of 10 minutes you've only processed about 300 messages.

**Comment by nirbenda** [comment] 2019-02-27 10:10
Hi @callmehiphop , thanks for looking into this.
Yes, as it is a message every 2 seconds and it takes about 5 minutes to happen so it is about 150-300 messages being processed.

**Comment by callmehiphop** [comment] 2019-02-27 10:27
I guess what I'm trying to get at is if your application is *expecting* about 30 messages per minute. One possible cause of a memory leak could be the clients flow control mechanisms not functioning properly, but in this case that seems unlikely given the low number of pending messages.

**Comment by nirbenda** [comment] 2019-02-27 10:32
After a while I get this heap out of memory message:

```

<--- Last few GCs --->

[10224:000002CE21274B00]  1212560 ms: Mark-sweep 1849.2 (1976.9) -> 1849.2 (1945.9) MB, 2901.2 / 1.2 ms  last resort GC in old space requested
[10224:000002CE21274B00]  1215427 ms: Mark-sweep 1849.2 (1945.9) -> 1849.2 (1945.9) MB, 2866.6 / 1.6 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000000B109EA57C1 <JSObject>
    2: /* anonymous */(aka /* anonymous */) [H:\ReteAI\tmp\node_modules\@google-cloud\pubsub\build\src\subscriber.js:22] [bytecode=0000024CC02AECF9 offset=75](this=000003EC16E822D1 <undefined>,resolve=000001CD103DE3B9 <JSFunction (sfi = 000003EC16EACD21)>,reject=000001CD103DE401 <JSFunction (sfi = 000003EC16EACE81)>)
    3: new Promise(aka Promise)(this=000003EC16E82311 <the_hole>,000001CD103D...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::NewUninitializedFixedArray
 5: v8::internal::JSReceiver::GetOwnPropertyDescriptor
 6: v8::internal::JSReceiver::GetOwnPropertyDescriptor
 7: v8::internal::StringHasher::ComputeUtf8Hash
 8: v8::internal::StringHasher::ComputeUtf8Hash
 9: v8::internal::operator<<
10: v8::internal::operator<<
11: v8::internal::operator<<
12: v8::internal::operator<<
13: v8::internal::operator<<
14: v8::internal::operator<<
15: 0000039A71D843C1
```

**Comment by callmehiphop** [comment] 2019-02-27 12:23
@nirbenda so far I haven't been able to reproduce the issue you're seeing. I thought maybe it was specific to Windows, but my PC runs your reproduction code well enough and memory seems to sit around 60MB on my machine.

I'm running the following publisher script at the same time to try and emulate getting 1 message every 2 seconds.

```js
const {PubSub} = require('@google-cloud/pubsub');
const pubsub = new PubSub();

const topic = pubsub.topic('my-topic', {
  batching: {maxMilliseconds: 0}
});

const message = Buffer.from('Hello, world!');

setInterval(() => topic.publish(message), 2000);
```

Is there anything I could do differently that could give me the errors you're seeing?

**Comment by nirbenda** [comment] 2019-02-27 13:19
Maybe some of the inner dependency versions? Maybe legacy installed packaged are causing this.
Here is the 'npm list':
```

-- @google-cloud/pubsub@0.25.0
  +-- @google-cloud/paginator@0.1.2
  | +-- arrify@1.0.1 deduped
  | +-- extend@3.0.2 deduped
  | +-- is@3.3.0 deduped
  | +-- split-array-stream@2.0.0
  | | `-- is-stream-ended@0.1.4 deduped
  | `-- stream-events@1.0.5
  |   `-- stubs@3.0.0
  +-- @google-cloud/projectify@0.3.2
  +-- @google-cloud/promisify@0.4.0
  +-- arrify@1.0.1
  +-- async-each@1.0.1
  +-- delay@4.1.0
  +-- duplexify@4.0.0
  | +-- end-of-stream@1.4.1
  | | -- once@1.4.0
  | |   -- wrappy@1.0.2
  | +-- inherits@2.0.3
  | +-- readable-stream@3.1.1
  | | +-- inherits@2.0.3 deduped
  | | +-- string_decoder@1.2.0
  | | | -- safe-buffer@5.1.2 deduped
  | | -- util-deprecate@1.0.2
  | -- stream-shift@1.0.0
  +-- extend@3.0.2
  +-- google-auth-library@3.1.0
  | +-- base64-js@1.3.0
  | +-- fast-text-encoding@1.0.0
  | +-- gaxios@1.7.0
  | | +-- abort-controller@2.0.2
  | | | `-- event-target-shim@5.0.1
  | | +-- extend@3.0.2 deduped
  | | +-- https-proxy-agent@2.2.1 deduped
  | | `-- node-fetch@2.3.0
  | +-- gcp-metadata@0.9.3
  | | +-- gaxios@1.7.0 deduped
  | | `-- json-bigint@0.3.0
  | |   `-- bignumber.js@7.2.1
  | +-- gtoken@2.3.2
  | | +-- gaxios@1.7.0 deduped
  | | +-- google-p12-pem@1.0.3
  | | | +-- node-forge@0.7.6
  | | | `-- pify@4.0.1 deduped
  | | +-- jws@3.2.1 deduped
  | | +-- mime@2.4.0
  | | `-- pify@4.0.1
  | +-- https-proxy-agent@2.2.1
  | | +-- agent-base@4.2.1
  | | | `-- es6-promisify@5.0.0
  | | |   `-- es6-promise@4.2.6
  | | `-- debug@3.2.6
  | |   `-- ms@2.1.1
  | +-- jws@3.2.1
  | | +-- jwa@1.3.0
  | | | +-- buffer-equal-constant-time@1.0.1
  | | | +-- ecdsa-sig-formatter@1.0.11
  | | | | `-- safe-buffer@5.1.2 deduped
  | | | `-- safe-buffer@5.1.2 deduped
  | | `-- safe-buffer@5.1.2
  | +-- lru-cache@5.1.1
  | | `-- yallist@3.0.3
  | `-- semver@5.6.0
  +-- google-gax@0.25.3
  | +-- @grpc/grpc-js@0.3.5
  | | `-- semver@5.6.0 deduped
  | +-- @grpc/proto-loader@0.4.0
  | | +-- lodash.camelcase@4.3.0
  | | `-- protobufjs@6.8.8 deduped
  | +-- duplexify@3.7.1 extraneous
  | +-- google-auth-library@3.1.0 deduped
  | +-- google-proto-files@0.18.0
  | | +-- protobufjs@6.8.8 deduped
  | | `-- walkdir@0.0.12 extraneous
  | +-- grpc@1.18.0
  | | +-- lodash.camelcase@4.3.0 deduped
  | | +-- lodash.clone@4.5.0
  | | +-- nan@2.12.1
  | | +-- node-pre-gyp@0.12.0 extraneous
  | | `-- protobufjs@5.0.3 extraneous
  | +-- grpc-gcp@0.1.1
  | | +-- grpc@1.18.0 deduped
  | | `-- protobufjs@6.8.8 deduped
  | +-- is-stream-ended@0.1.4 deduped
  | +-- lodash.at@4.6.0
  | +-- lodash.has@4.5.2
  | +-- protobufjs@6.8.8 deduped
  | +-- retry-request@4.0.0
  | | `-- through2@2.0.5 extraneous
  | +-- semver@5.6.0 deduped
  | `-- walkdir@0.3.2
  +-- is@3.3.0
  +-- is-stream-ended@0.1.4
  +-- lodash.chunk@4.2.0
  +-- lodash.merge@4.6.1
  +-- lodash.snakecase@4.1.1
  +-- p-defer@1.0.0
  +-- protobufjs@6.8.8
  | +-- @protobufjs/aspromise@1.1.2
  | +-- @protobufjs/base64@1.1.2
  | +-- @protobufjs/codegen@2.0.4
  | +-- @protobufjs/eventemitter@1.1.0
  | +-- @protobufjs/fetch@1.1.0
  | | +-- @protobufjs/aspromise@1.1.2 deduped
  | | `-- @protobufjs/inquire@1.1.0 deduped
  | +-- @protobufjs/float@1.0.2
  | +-- @protobufjs/inquire@1.1.0
  | +-- @protobufjs/path@1.1.2
  | +-- @protobufjs/pool@1.1.0
  | +-- @protobufjs/utf8@1.1.0
  | +-- @types/long@4.0.0
  | +-- @types/node@10.12.27
  | `-- long@4.0.0
  `-- through2@3.0.0
    +-- readable-stream@3.1.1 deduped
    `-- xtend@4.0.1

npm ERR! extraneous: duplexify@3.7.1 H:\ReteAI\tmp\node_modules\google-gax\node_modules\duplexify
npm ERR! extraneous: walkdir@0.0.12 H:\ReteAI\tmp\node_modules\google-proto-files\node_modules\walkdir
npm ERR! extraneous: node-pre-gyp@0.12.0 H:\ReteAI\tmp\node_modules\grpc\node_modules\node-pre-gyp
npm ERR! extraneous: protobufjs@5.0.3 H:\ReteAI\tmp\node_modules\grpc\node_modules\protobufjs
npm ERR! extraneous: through2@2.0.5 H:\ReteAI\tmp\node_modules\retry-request\node_modules\through2
```

**Comment by callmehiphop** [comment] 2019-02-27 14:28
@nirbenda Our dependency list looks the same, although I'm not getting any `extraneous` errors. Are you running `npm dedupe` or using any additional Google Cloud Node.js clients in the same project?

**Comment by nirbenda** [comment] 2019-02-27 20:35
I got this problem on another project I have, but I had created this totally separated project that includes only the code I presented above.

**Comment by ajaaym** [comment] 2019-02-27 20:48
@nirbenda this might not make any difference, but can you try loading ```const {PubSub} = require('@google-cloud/pubsub');``` outside function?

```
var http = require('http');
 const {PubSub} = require('@google-cloud/pubsub');
async function listenForErrors(subscriptionName) {

```

**Comment by callmehiphop** [comment] 2019-02-27 21:10
@nirbenda Could you share your `package-lock.json` file?

**Comment by nirbenda** [comment] 2019-02-27 21:22
@ajaaym , tried to do what you offered, same results :(.
@callmehiphop , here is my package-lock.json (renamed to .txt)


[package-lock.txt](https://github.com/googleapis/nodejs-pubsub/files/2912361/package-lock.txt)

**Comment by callmehiphop** [comment] 2019-02-28 12:29
Unfortunately I'm still unable to reproduce :( would you mind testing with older versions of the client? If we can find the last version that does not produce this error it might help us to determine what changes could be causing it.

**Comment by nirbenda** [comment] 2019-02-28 13:07
@callmehiphop  Sure, which version do you suggest to start from?

**Comment by callmehiphop** [comment] 2019-02-28 13:17
Lets try with the following

* 0.24.1
* 0.23.0
* 0.22.2

**Comment by nirbenda** [comment] 2019-02-28 21:14
@callmehiphop In version 0.24.1 I could not reproduce this issue. I will let it work for a couple of hours just to be sure.
Which version do you think it is best to check next?

**Comment by callmehiphop** [comment] 2019-02-28 21:18
@nirbenda I don't think there's any need to check other versions, I'm going to go through the commits between 0.24.1 and 0.25.0 and see if there's anything obvious that might be causing the issue. Thanks for testing it out!

**Comment by nirbenda** [comment] 2019-03-01 01:58
@callmehiphop unfortunately, it took longer but it happened also in 0.24.1 as well.
I will check the other versions now.

**Comment by nirbenda** [comment] 2019-03-01 06:31
@callmehiphop In version 0.23.0 it doesn't seem to reproduce, I am having another issue after running for a while (ERROR: error: 14 UNAVAILABLE: TCP Read failed) but I think this might be already fixed in newer versions.
I tracked the memory usage and it seems to be stable (below 40MB).
So I think it might be something between 0.23.0 and 0.24.1.
Thanks :)

**Comment by callmehiphop** [comment] 2019-03-04 21:30
@nirbenda thanks for the report! It looks like between 0.23.0 and 0.24.1 we upgraded 2 of our core dependencies. I suspect the issue is coming from one of them, but I'm probably going to need your help determining which one since I've been largely unsuccessful at reproducing your issue so far 😢 

The dependencies in question are:

* [google-gax](https://github.com/googleapis/nodejs-pubsub/pull/444)
* [google-auth-library](https://github.com/googleapis/nodejs-pubsub/pull/433)

It looks like neither one required a code change, so we should be able to just rollback the version in order to test.

**Comment by nirbenda** [comment] 2019-03-06 07:43
I tried reverting those two libraries to previous versions, but the memory leak still occurred after a while.
Now I have reverted again to 0.23.0 just to be sure that it does not happen.
Any other idea?

**Comment by nirbenda** [comment] 2019-03-06 08:52
@callmehiphop By the way, on the 0.23.0 version I get this error EXACTLY after 900 messages (checked twice), therefore it is problematic to check a long-running process. Although monitoring the memory in the 0.23.0 version seems to show now indication of a memory leak.
Any other ideas?
```

Message: [object Object] 895
Message: [object Object] 896
Message: [object Object] 897
Message: [object Object] 898
Message: [object Object] 899
Message: [object Object] 900
ERROR: Error: 14 UNAVAILABLE: TCP Read failed
ERROR: Error: 14 UNAVAILABLE: TCP Read failed
ERROR: Error: 14 UNAVAILABLE: TCP Read failed
ERROR: Error: 14 UNAVAILABLE: TCP Read failed
ERROR: Error: 14 UNAVAILABLE: TCP Read failed

```

**Comment by callmehiphop** [comment] 2019-03-06 18:52
I'm a bit of a loss really, being unable to reproduce makes it almost impossible to determine the issue. If I had to speculate I would think the memory leak would come from 1 of 2 places

* Subscription flow control bug
* Native grpc error

Which would lead me to guess that this might be a grpc error since we've kind of ruled out the possibility of a flow control bug. @nirbenda if you want to try and profile the memory leak and give us back results that might help? Otherwise maybe we should try and pull in another pair of eyes. @stephenplusplus do you have any bandwidth to try and reproduce this?

**Comment by callmehiphop** [comment] 2019-03-18 19:41
@JustinBeckwith is there anyone else we could try and pull in on this to attempt a repro?

**Comment by callmehiphop** [comment] 2019-04-22 19:22
Hasn't been any activity here in quite some time, I'm going to close this for now. If any new info becomes available I'll be more than happy to re-open and investigate again.

**Closed by callmehiphop** 2019-04-22 19:22 UTC
Labels: help wanted, needs more info, priority: p2, type: bug
