### ISSUE TITLE
modifyAckDeadline fails with Request payload size exceeds the limit: 524288 bytes when it gets called with too many messages

### ISSUE THREAD

**Issue by mkls** [googleapis/nodejs-pubsub#1366] opened 2021-08-06 11:28 UTC
#### Environment details

  - OS: Kubernetes Engine
  - Node.js version: 14.16.0
  - npm version: -
  - `@google-cloud/pubsub` version: 2.5.0

#### Steps to reproduce

  1. Consume multiple stream from the same machine where the sum of `{ flowControl: { maxMessages: <count>} }` is at least 3000
  2. Subscribe to subscription error events with `subscription.on('error', () => {})`
  3. Occasionally you will get errors like `Failed to "modifyAckDeadline" for 2791 message(s). Reason: 3 INVALID_ARGUMENT: Request payload size exceeds the limit: 524288 bytes.` 

There was already an issue for this kind of error: https://github.com/googleapis/nodejs-pubsub/issues/62
Which also had a solution: https://github.com/googleapis/nodejs-pubsub/pull/65
The issue seems to be that the selected value for MAX_ACK_IDS_PER_REQUEST is probably too large (https://github.com/googleapis/nodejs-pubsub/pull/65/files#diff-22597dec0f27f27ae05243ae8a33dbd2b355f8146698989334bdc000877cd5a0R41)

From our logs it looks like it should be around 2500 instead of 3000.

![Screenshot 2021-08-06 at 13 26 59](https://user-images.githubusercontent.com/5834480/128503755-bb6933fa-877d-43fd-ade2-fb645f7d73ea.png)

**Comment by mkls** [comment] 2021-08-06 11:49
I've realized that the lib changed since the referenced modification, and now this default 3000 batch size can be overridden with { batching: { maxMessages: <x> } subscription options.
Going to test if changing this value actually makes these errors disappear.

**Comment by mkls** [comment] 2021-08-06 14:56
setting `{ batching: { maxMessages: 2500 }` seems to make these errors go away.
I would suggest changing the default to 2500 here: https://github.com/googleapis/nodejs-pubsub/blob/master/src/message-queues.ts#L185.
Or since there is a workaround available I guess this ticket can be closed.

**Comment by feywind** [comment] 2022-03-24 19:41
Given that stack trace, this seems like something that might need a grpc option if we want to support it.

@kamalaboulhosn did I bug you about this one already?

**Comment by kamalaboulhosn** [comment] 2022-03-24 20:51
I don't think we need a grpc option here. I think we just need to make sure batches of modacks don't exceed the size limit.

**Comment by feywind** [comment] 2022-08-15 19:51
This came up recently as something that's not consistent across language libraries for Pub/Sub, so I'm moving it to feature request.

**Comment by feywind** [comment] 2023-01-31 20:05
We have moved this issue to our internal tracking system. However, the issue is considered low-priority at this time. If the issue is ultimately resolved, it will appear in the release notes for the client at that time. If this issue is of higher priority for you, please enter a [support ticket](https://cloud.google.com/support/) for follow-up. Thanks.

(ref bug 267340848)

**Closed by feywind** 2023-01-31 20:05 UTC
Labels: type: feature request, external, api: pubsub

**Comment by AnandShiva** [comment] 2024-09-13 13:41
Is this released yet? Still facing this issue with the latest pub sub and grpc version.

**Comment by feywind** [comment] 2024-09-13 18:19
The 4.7.2 release should fix this, just released a moment ago.

**Comment by AnandShiva** [comment] 2024-09-15 05:31
thanks for the update @feywind! 
Checking it out.
