### ISSUE TITLE
subscription.on stops receiving messages

### ISSUE THREAD

**Issue by slavoroi** [googleapis/nodejs-pubsub#557] opened 2019-03-21 07:34 UTC
#### Environment details

  - OS: linux mint 17.3/ ubuntu 16.04
  - Node.js version: 8.12.0 / 8.9.4
  - npm version: 6.9.0
  - `@google-cloud/pubsub` version: 0.28.1 / 0.24.1

Listening to a subscription stops receiving messages after a random amount of time or a certain peak. 
It all works well when we have dozens of messages in the queue (small queue with minimum activity). 
No errors are received.
client.pull(request) works well and gets requests.

```javascript
const pubSub = new PubSub({projectId: GCP_PROJECT_ID});
const subscription = pubSub.subscription(queue); 
// Also tried flow control options,  flowControl: {maxBytes: 1000,   maxMessages:1 }
subscription.on('message', messageHandler);
subscription.on('error', (err) => {
      setImmediate(() => handleError(err));
});
```
#### Steps to reproduce

  1. Subscribe to a certain queue
  2. Wait for many messages to arrive.
  3. messages stops getting received.

What are we doing wrong?
Is there a workaround?
Is there 

Thanks!

**Comment by callmehiphop** [comment] 2019-03-21 07:57
I think this is a duplicate of https://github.com/googleapis/nodejs-pubsub/issues/468. I might have a fix via https://github.com/googleapis/nodejs-pubsub/pull/556 if you have the bandwidth to test, otherwise I would subscribe to that issue for now.

**Closed by callmehiphop** 2019-03-21 07:57 UTC
Labels: status: duplicate, type: bug
