### ISSUE TITLE
DEADLINE_EXCEEDED on subscriber

### ISSUE THREAD

**Issue by skk2142** [googleapis/nodejs-pubsub#1276] opened 2021-05-02 23:35 UTC
#### Environment details

  - OS: Node 12.8.2:alpine docker image
  - npm version: 
  - `@google-cloud/pubsub` version: 2.11.0

#### Steps to reproduce

All the message being received by a subscriber throws this error
```
{"serviceName":"notification","ackIds":["id1", "id2",...],"code":4,"details":"Deadline Exceeded","metadata":{"_internal_repr":{},"flags":0},"stack":"Error: Failed to \"modifyAckDeadline\" for 3 message(s). Reason: 4 DEADLINE_EXCEEDED: Deadline Exceeded\n    at /app/node_modules/@google-cloud/pubsub/src/message-queues.ts:258:15","message":"Failed to \"modifyAckDeadline\" for 3 message(s). Reason: 4 DEADLINE_EXCEEDED: Deadline Exceeded","severity":"error"}
```
I have tried to use `new PubSub({ grpc });` with grpc version "^1.24.7" and `new PubSub({})` and I get the same error in both cases. I have made sure that the IAM policies are correct.

**Comment by feywind** [comment] 2021-05-04 19:07
@skk2142 Thanks for the report! Can you give some more details about how you're calling the library? (Ideally a code snippet.) Also, I assume that _some_ of the calls are going through, since there's a deadline modify call being attempted? Do you know if there's any correlation between the amount of time it's been running and the errors happening? Also do you know if other calls succeed after you see that error, or does all communication with the Pub/Sub service stop?

**Comment by skk2142** [comment] 2021-05-04 21:00
Publishing messages is not a problem. It only occurs for subscribers for every message, right from the first message that it receives. Because pubsub reattempts delivery, I get the error multiple times. Interestingly, when I used to option
```
{
    streamingOptions: {
      maxStreams: 1,
    },
  }
```
to create the subscription, the error seems to disappear. However, I am not sure if that's the right thing to do or how it will affect the things in production.

```typescript
// private pubsubClient = new PubSub({ grpc });
this.consumerTopics = [...topics];
topics.forEach(async (topicName) => {
  const [topic] = await this.pubsubClient
    .topic(topicName)
    .get({ autoCreate: true });
  const subscriptionName = `${
    this.config.serviceName
  }-${topicName}${args.isDarkRelease ? "-dark" : ""}`;
  let subscription = await topic.subscription(
    subscriptionName,
  );
  const [exist] = await subscription.exists();
  if (!exist) {
    [subscription] = await subscription.create({
      filter: !args.isDarkRelease
        ? `NOT attributes:x-prop-${this.config.serviceName}-dark`
        : `attributes:x-prop-${this.config.serviceName}-dark`,
    });
    this.logger.info(
      `Subscription created: ${subscriptionName}`
    );
  }
  this.subscribeTopics[topicName] = subscription;
  subscription.on("message", async (message: Message) => {
    const data: {
      id: string;
      [key: string]: any;
    } = JSON.parse(message.data.toString());
    this.logger.info(
      `Event received ${topicName}; ${message.attributes["x-request-id"]}`
    );
    const eventData = await this.consumeValidator?.extractData(
      topicName,
      data
    );
    try {
      await cb(
        { key: topicName, data: eventData },
        getPropHeaders(message.attributes),
        data
      );
      message.ack();
    } catch (e) {
      this.logger.error(e);
      message.nack();
    }
  });
  // @ts-ignore
  subscription.on("error", (err) => {
    this.logger.error(err);
  });
```

**Comment by skk2142** [comment] 2021-05-19 14:48
No! @feywind Any updates on this? Is using this option safe for production volume?
```
streamingOptions: {
    maxStreams: 1,
  }
```

**Comment by skk2142** [comment] 2021-05-25 20:38
Any update on this? It's a bit disappointing that this library does not work out of the box given pubsub is a stable product and nodejs is one of the most widely used framework.

**Comment by LucasKeiti28** [comment] 2021-05-25 20:48
I'm with the same issue... some update here?

**Comment by LucasKeiti28** [comment] 2021-05-26 12:38
I could workaround the error by decreasing the number of subscribers the PubSub is handling.

When I had around 25 subscribers I was receiving the error:
`(node:1) UnhandledPromiseRejectionWarning: Error: Failed to "modifyAckDeadline" for 1 message(s). Reason: 4 DEADLINE_EXCEEDED: Deadline exceeded`

So I optimized how I was handling the topics/subscribers, using around 12 subscribers, and the error is gone.

But it's not the solution to all cases.

**Comment by skk2142** [comment] 2021-06-16 17:36
Hi @feywind Any updates on this? I've been using
```
streamingOptions: {
    maxStreams: 1,
  }
```
option. Is it ready for high volume workload? What does this option even do?

**Comment by feywind** [comment] 2021-06-22 21:13
@crwilcox Here's another `DEADLINE_EXCEEDED` issue, potentially?

@skk2142 It looks like that has to do with the maximum number of streams in use for streaming pull. So with a setting of 1, you'd basically only receive one message at a time. I'm not sure I'd want to rely on that for a high volume workload, but if it stops the problem, it's probably an okay workaround until we can figure out what's causing it.

@LucasKeiti28 This actually sounds a but like another issue I've been working on... each PubSub object has a limit of 100 streams, and some other folks were having issues with hitting 25 connections. Some thoughts from that:

> The question in that bug seems to be about the 100 streams per connection limit, which is a GFE limit that applies to all clients. The Spanner client library addresses that limit by using the grpc-gcp library/plugin, which automatically creates additional connections to stay under that limit.

We're not currently doing that in Pub/Sub, and I haven't looked into it. It might be a useful bread crumb though.

Maybe also related:

> In general, lots of subscriptions in each client is a bit of an anti-pattern.

We'd need to talk about the specific use case though, to figure out the best way around that.

**Comment by madeindjs** [comment] 2021-06-23 15:16
I reproduce error with this minimal sample.

Here the publisher:

~~~js
// variable.js
const {PubSub} = require("@google-cloud/pubsub");

const pubsub = new PubSub({  projectId: "mazen-158916",  keyFile: "key.json",});
const topicName = "alexandre-testing";

async function getTopic() {
  const [topic] = await pubsub.topic(topicName).get({autoCreate: true});
  return topic;
}

module.exports = {  pubsub,  getTopic,};
~~~

~~~js
// publish.js
const {getTopic} = require("./variables");

async function publishMessage(topic) {
  const dataBuffer = Buffer.from(JSON.stringify({content: "Hello World", date: new Date()}));
  await topic.publish(dataBuffer);
  process.stdout.write(".");
}

async function main() {
  const topic = await getTopic();
  setInterval(() => publishMessage(topic), 1000);
}

main().catch(console.error);
~~~

and the subscriber. I intentionnaly wait 20 seconds to responds (default `ackDeadline` is 10s)

~~~js
// subscribe.js
const {getTopic, pubsub} = require("./variables");

async function main() {
  const topic = await getTopic();

  const [subscription1] = await pubsub
    .subscription(`alexandre-testing-subscription-${new Date().getTime()}`, { topic,})
    .get({autoCreate: true});

  subscription1.on("message", (message) => {
    console.log(
      `get message #${message.id} -- receive %o`,
      JSON.parse(message.data.toString())
    );

    setTimeout(() => {
      console.log(`ack message #${message.id}`);
      message.ack();
    }, 20_000);
  });
}

main().catch(console.error);
~~~

Output let me think that everything goes well

~~~
get message #2574927903389364 -- receive { content: 'Hello World', date: '2021-06-23T15:05:08.726Z' }
...
ack message #2574927903389364
~~~

But message are stuck 

![image](https://user-images.githubusercontent.com/11815139/123122635-7aebb900-d446-11eb-92a7-72bb88c2f304.png)

If I restart `node subscribe.js`, I can't get them again...

**Comment by skk2142** [comment] 2021-06-29 15:39
Hi @feywind I really want to continue using PubSub for it's features but I'm approaching close to releasing the application to a larger user base and am concerned if the issue would be fixed anytime soon. Is there a timeline on when the issue would be fixed? Also, until the issue is fixed, is using `maxStreams: 25` a safe option?

**Comment by skk2142** [comment] 2021-07-07 18:31
It's been more than two months since this issue has been opened. The library is not ready for high volume workload. And yet there are not updates. Shouldn't this be high priority? Is this being worked on?

**Comment by feywind** [comment] 2021-07-07 19:06
@skk2142 It definitely is, yeah. The `maxStreams` fix should be safe to use for the moment. There's an effort to track down `DEADLINE_EXCEEDED` errors across several libraries, actually. @crwilcox is this related to that?

**Comment by skk2142** [comment] 2021-07-07 19:20
Thanks. What's the maximum value of maxStream that we can currently safely use and how many concurrent messages can it handle in proportion to the number of maxStreams?

**Comment by feywind** [comment] 2021-07-07 19:36
@skk2142 It looks like the built-in limit of streams per connection is 100, so 25 would be a conservative value.

There isn't a limit on connections, as far as I know, but it would require a separate `PubSub` object per connection, so you couldn't share object handles between them. I know there's someone working on an analysis of optimal settings in regards to streams/connections, but I'm not sure what the status is on that.

Another thing that might help is publisher flow control, if you're receiving too many messages to ack in a timely manner. That's not in the library yet, but I'm working on an implementation of it now.

**Comment by skk2142** [comment] 2021-07-07 19:41
I see. Thanks I'll try using 25 and will report if I face any issues.

**Comment by feywind** [comment] 2021-07-07 19:44
I was asking one of our service folks, and he said that the publisher and subscriber should ideally be completely decoupled. So disregard my publisher flow control comment, sorry.

**Comment by kamalaboulhosn** [comment] 2021-07-07 20:22
It sounds to me like this is a case of the client getting overwhelmed and not being able to send acks and modacks back. Let me mention some things about the properties discussed so far:

`maxStreams` controls the number of streaming pull streams that are open to the client. This number should not really be set to a higher value unless it is believed that the client itself can handle more messages, but a single stream is not able to deliver enough. A single stream can deliver 10MB/s as per the [resource limits](https://cloud.google.com/pubsub/quotas#resource_limits). Limiting to a single stream will not limit one to receiving a single message at a time.

It is possible that the subscriber is becoming overwhelmed with the amount of data it is receiving. If this is the case, then increasing `maxStreams` will likely make the problem worse. What you want to do is to try to limit the number of messages your subscriber is handling at once. Reducing `maxStreams` is a more advanced way to do this. The best way to do it is to change the [flow control settings](https://cloud.google.com/pubsub/docs/samples/pubsub-subscriber-flow-settings#pubsub_subscriber_flow_settings-nodejs). With flow control settings reduced, there would be fewer messages delivered to the client at the same time. This would help if the issue is that overload due to how the messages are being processed is what is causing the failed RPCs to the server.

There could be many different things that could contribute to an overloaded subscriber. It may not even be the subscriber itself that is overloaded, it could be that it is on an overloaded machine. Does the docker container contain anything else that is running and could be using up CPU, RAM, or network resources? What about the machine it runs on? Also, depending on where and how you are running the subscriber, it could be that the type of VM has limited throughput and therefore the requests are unable to get sent. 

There are some Medium posts that may be of interest:
* [Fine-tuning Pub/Sub performance with batch and flow control settings](https://medium.com/google-cloud/pub-sub-flow-control-batching-9ba9a75bce3b)
* [Testing Cloud Pub/Sub clients to maximize streaming performance](https://cloud.google.com/blog/products/data-analytics/testing-cloud-pubsub-clients-to-maximize-streaming-performance)

**Comment by meredithslota** [comment] 2021-10-06 00:12
It seems like possibly @kamalaboulhosn's comments above solved the user issues described in this issue. I'm closing due to no follow-up since but please reply if this does not address your issue. Thanks!

**Closed by meredithslota** 2021-10-06 00:12 UTC
Labels: priority: p2, type: bug, api: pubsub
