### ISSUE TITLE
Pub/Sub retry settings: needs common api between data & admin ops, better docs.

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-pubsub#35] opened 2018-01-09 18:27 UTC
###### Copied from original issue: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2788

<a href="/kir-titievsky"><img src="https://avatars2.githubusercontent.com/u/18533398?s=88&v=4" height=44 width=44 align=left></a>@kir-titievsky<br>January 9, 2018 4:42 PM

This is a bug to track progress on an email discussion about setting custom retry settings. 

Previous suggestion:
In src/v1/publisher_client.js the gapicConfig contains the contents of the config file you mentioned, and it is passed down to gaxGrpc:

https://github.com/googleapis/nodejs-pubsub/blob/96fd4d6347ca0546a8b8581c1db61e2edb0548d8/src/v1/publisher_client.js#L166

    var defaults = gaxGrpc.constructSettings(
      'google.pubsub.v1.Publisher',
      gapicConfig,
      opts.clientConfig,
      {'x-goog-api-client': clientHeader.join(' ')}
    );
Here the third parameter, opts.clientConfig, gives configOverrides to gaxGrpc.constructSettings, and, given the name, I guess it might be able to override options.
opts.clientConfig comes from PublisherClient constructor parameter. So I guess you might try settings opts.clientConfig to override any default configuration.

If it does not work for you, please let me know - better with code example - and I'll create an issue for pubsub package.

**Comment by jonparrott** [comment] 2018-02-09 19:10
@kir-titievsky do you think this is release blocking? Does this affect the interface or is it something that can be changed post v1.0.0 without necessitating a major version bump?

**Comment by kir-titievsky** [comment] 2018-02-12 15:25
I think this is release blocking, unless we are convinced that offering a consistent retry settings API across all operations will not require client library API changes.

**Comment by stephenplusplus** [comment] 2018-02-12 15:35
Anything that is passed to the PubSub constructor gets passed to PublisherClient. Has the issue reporter try the suggestion from the end of the opening post in this thread? (Seems like we are only seeing a piece of the conversation)

**Comment by callmehiphop** [comment] 2018-12-04 00:42
@kinwa91 I'm actually not 100% what the issue is describing, haha..

In regards to gapics, I can't tell if gax actually uses/caches any call options passed in via the client constructor, but as far as I can tell, it does not.

If this is about the hand-written Publisher client, it should be resolved.

**Comment by callmehiphop** [comment] 2019-05-15 20:33
I think as far as providing publishing call options, this has been solved for a while. We could probably improve the client with the steps outlined in https://github.com/googleapis/google-cloud-node/issues/2895, but I'll let @kir-titievsky make the call if that should hold up GA or not. Going to close this issue, but please feel free to re-open if you disagree!

**Closed by callmehiphop** 2019-05-15 20:33 UTC
Labels: status: blocked, triaged for GA, type: question

**Comment by sduskis** [comment] 2019-05-15 23:59
We should do a thorough review of the API before we go GA.  We ought to do that sooner rather than later.  I'll bring it up with Kir and crew.
