### ISSUE TITLE
Unexpected Error 13: GOAWAY error while using gRPC

### ISSUE THREAD

**Issue by samiislam600** [googleapis/nodejs-pubsub#389] opened 2018-12-05 18:03 UTC
Issue summary: The GOAWAY error returning from pubSub which originates from gRPC Client library.

The OS for both container and the compute instance is Debian 9
Client Library PubSub node.js latest 0.20.1 version
The customer has configured pubsub messages as a service node. The payload of the received message is used in the following format.

\"depth_limit\": 3, \"run_id\":
\"c8d503f18024e03f97b617b1cb54fcd92594bfdcf678a7cb4a401867\", \"url\": \"
https://example.com", \"current_depth\": 1, \"retries\": 0,
\"only_allow_match\": \"example.com\"}

Then the code pushes message to pubsub with the following payload:

{run_id: config.get("RUN_ID"), website_url: target_url, screenshot_url:
storage_file_url, timestamp: now}

There is error 13 GOAWAY error thrown while using gRPC according to the following logs. 
{"error":{},"level":"error","message":"uncaughtException: unhandledRejection: Error: 13 INTERNAL: GOAWAY received\n    at Object.exports.createStatusError (/home/jsworker/js_screenshot/node_modules/grpc/src/common.js:87:15)\n    at Object.onReceiveStatus (/home/jsworker/js_screenshot/node_modules/grpc/src/client_interceptors.js:1188:28)\n    at InterceptingListener._callNext (/home/jsworker/js_screenshot/node_modules/grpc/src/client_interceptors.js:564:42)\n    at InterceptingListener.onReceiveStatus (/home/jsworker/js_screenshot/node_modules/grpc/src/client_interceptors.js:614:8)\n    at callback (/home/jsworker/js_screenshot/node_modules/grpc/src/client_interceptors.js:841:24), [object Promise]\nError: unhandledRejection: Error: 13 INTERNAL: GOAWAY received\n    at Object.exports.createStatusError (/home/jsworker/js_screenshot/node_modules/grpc/src/common.js:87:15)\n    at Object.onReceiveStatus (/home/jsworker/js_screenshot/node_modules/grpc/src/client_interceptors.js:1188:28)\n    at InterceptingListener._callNext (/home/jsworker/js_screenshot/node_modules/grpc/src/client_interceptors.js:564:42)\n    at InterceptingListener.onReceiveStatus (/home/jsworker/js_screenshot/node_modules/grpc/src/client_interceptors.js:614:8)\n    at callback (/home/jsworker/js_screenshot/node_modules/grpc/src/client_interceptors.js:841:24), [object Promise]\n    at process.on (/home/jsworker/js_screenshot/worker.js:60:13)\n    at emitTwo (events.js:126:13)\n    at process.emit (events.js:214:7)\n    at emitPendingUnhandledRejections (internal/process/promises.js:108:22)\n    at runMicrotasksCallback (internal/process/next_tick.js:125:9)\n    at _combinedTickCallback (internal/process/next_tick.js:132:7)\n    at process._tickCallback (internal/process/next_tick.js:181:9)","stack":"Error: unhandledRejection: Error: 13 INTERNAL: GOAWAY received\n    at Object.exports.createStatusError (/home/jsworker/js_screenshot/node_modules/grpc/src/common.js:87:15)\n    at Object.onReceiveStatus (/home/jsworker/js_screenshot/node_modules/grpc/src/client_interceptors.js:1188:28)\n    at InterceptingListener._callNext (/home/jsworker/js_screenshot/node_modules/grpc/src/client_interceptors.js:564:42)\n    at InterceptingListener.onReceiveStatus (/home/jsworker/js_screenshot/node_modules/grpc/src/client_interceptors.js:614:8)\n    at callback (/home/jsworker/js_screenshot/node_modules/grpc/src/client_interceptors.js:841:24), [object Promise]\n    at process.on (/home/jsworker/js_screenshot/worker.js:60:13)\n    at emitTwo (events.js:126:13)\n    at process.emit (events.js:214:7)\n    at emitPendingUnhandledRejections (internal/process/promises.js:108:22)\n    at runMicrotasksCallback (internal/process/next_tick.js:125:9)\n    at _combinedTickCallback (internal/process/next_tick.js:132:7)\n    at process._tickCallback (internal/process/next_tick.js:181:9)","exception":true,"date":"Sat Nov 10 2018 22:03:36 GMT+0000 (UTC)","process":{"pid":58,"uid":1000,"gid":1000,"cwd":"/home/jsworker/js_screenshot","execPath":"/usr/bin/node","version":"v8.12.0","argv":["/usr/bin/node","/home/jsworker/js_screenshot/worker.js"],"memoryUsage":{"rss":136372224,"heapTotal":47058944,"heapUsed":37265768,"external":1041197}},"os":{"loadavg":[44.3251953125,51.10888671875,53.1005859375],"uptime":851840},"trace":[{"column":15,"file":"/home/jsworker/js_screenshot/node_modules/grpc/src/common.js","function":"Object.exports.createStatusError","line":87,"method":"createStatusError","native":false},{"column":28,"file":"/home/jsworker/js_screenshot/node_modules/grpc/src/client_interceptors.js","function":"Object.onReceiveStatus","line":1188,"method":"onReceiveStatus","native":false},{"column":42,"file":"/home/jsworker/js_screenshot/node_modules/grpc/src/client_interceptors.js","function":"InterceptingListener._callNext","line":564,"method":"_callNext","native":false},{"column":8,"file":"/home/jsworker/js_screenshot/node_modules/grpc/src/client_interceptors.js","function":"InterceptingListener.onReceiveStatus","line":614,"method":"onReceiveStatus","native":false},{"column":24,"file":"/home/jsworker/js_screenshot/node_modules/grpc/src/client_interceptors.js","function":"callback","line":841,"method":null,"native":false},{"column":13,"file":"/home/jsworker/js_screenshot/worker.js","function":"process.on","line":60,"method":"on","native":false},{"column":13,"file":"events.js","function":"emitTwo","line":126,"method":null,"native":false},{"column":7,"file":"events.js","function":"process.emit","line":214,"method":"emit","native":false},{"column":22,"file":"internal/process/promises.js","function":"emitPendingUnhandledRejections","line":108,"method":null,"native":false},{"column":9,"file":"internal/process/next_tick.js","function":"runMicrotasksCallback","line":125,"method":null,"native":false},{"column":7,"file":"internal/process/next_tick.js","function":"_combinedTickCallback","line":132,"method":null,"native":false},{"column":9,"file":"internal/process/next_tick.js","function":"process._tickCallback","line":181,"method":"_tickCallback","native":false}],"timestamp":"2018-11-10 10:03:36 PM +0000"}

Log/Graph data: Worker 1 log "UncaughtException: unhandledRejection:error:13 Internal: GOAWAY received error"---->at Object.exports.createStatusError (/home/jsworker/js_screenshot/node_modules/grpc/src/common.js:87:15)
https://paste.googleplex.com/5337746553962496

The error is likely thrown from the package.json that uses gRPC line 60:13(Please check the worker 1 log that mentions it)
"google-gax": {
> "version": "0.19.0",
> "resolved": "
> https://registry.npmjs.org/google-gax/-/google-gax-0.19.0.tgz",
> "integrity":
> "sha512-CK7fSYCeGUUflNXpUNar9KPrvfsYLflxqJEt0KjCQLMfXoNossym5cUrAntBhcrMYJqIX9N8dNrUySh26xjpBg==",
> "requires": {
> "@grpc/grpc-js": "^0.2.0",
> "@grpc/proto-loader": "^0.3.0",
> "duplexify": "^3.6.0",
> "extend": "^3.0.1",
> "globby": "^8.0.1",
> "google-auth-library": "^1.6.1",
> "google-proto-files": "^0.16.0",
> "grpc": "^1.12.2",
> "is-stream-ended": "^0.1.4",
> "lodash": "^4.17.10",
> "protobufjs": "^6.8.8",
> "retry-request": "^4.0.0",
> "through2": "^2.0.3"
> },
>
 
"@google-cloud/pubsub": {
> "version": "0.20.1",
> "resolved": "
> https://registry.npmjs.org/@google-cloud/pubsub/-/pubsub-0.20.1.tgz",
> "integrity":
> "sha512-Ao88riLgl6KSk1+u8ukOzQxSe8p5LR/mS9BTnNWQdVr8+tntFZBKsb1k89ifdP0kU/TKHqPa2GHZfyLV5EYCJg==",
> "requires": {
> "@google-cloud/paginator": "^0.1.0",
> "@google-cloud/projectify": "^0.3.0",
> "@google-cloud/promisify": "^0.3.0",
> "arrify": "^1.0.0",
> "async-each": "^1.0.1",
> "delay": "^4.0.0",
> "duplexify": "^3.5.4",
> "extend": "^3.0.1",
> "google-auth-library": "^2.0.0",
> "google-gax": "^0.19.0",
> "google-proto-files": "^0.16.0",
> "is": "^3.0.1",
> "lodash.chunk": "^4.2.0",
> "lodash.merge": "^4.6.0",
> "lodash.snakecase": "^4.1.1",
> "protobufjs": "^6.8.1",
> "through2": "^2.0.3",
> "uuid": "^3.1.0"
> }
> },
>
The GOAWAY is explained in this documentation: 
GOAWAY error: https://http2.github.io/http2-spec/#GOAWAY

**Comment by sduskis** [comment] 2018-12-07 03:41
@stephenplusplus, any idea on how to fix this pesky GOAWAY?

**Comment by janisto** [comment] 2019-01-15 04:10
I get the same error with datastore, too.

```
    "@google-cloud/datastore": {
      "version": "2.0.0",
      "resolved": "https://registry.npmjs.org/@google-cloud/datastore/-/datastore-2.0.0.tgz",
      "integrity": "sha512-/sANJezizRK2HsKQZhfocAZmf6Q5wz609Fj8y9FxHncf23rPcEFOzArS0RgI4hweOPdfjBKfJ3LQLHkbtsRW1A==",
      "requires": {
        "@google-cloud/projectify": "^0.3.0",
        "@google-cloud/promisify": "^0.3.0",
        "arrify": "^1.0.1",
        "concat-stream": "^1.6.2",
        "create-error-class": "^3.0.2",
        "extend": "^3.0.1",
        "google-auth-library": "^2.0.0",
        "google-gax": "^0.20.0",
        "google-proto-files": "^0.16.0",
        "is": "^3.2.1",
        "lodash.flatten": "^4.4.0",
        "lodash.merge": "^4.6.1",
        "prop-assign": "^1.0.0",
        "split-array-stream": "^2.0.0",
        "stream-events": "^1.0.4",
        "through2": "^2.0.3"
      }
    },

    "google-gax": {
      "version": "0.20.0",
      "resolved": "https://registry.npmjs.org/google-gax/-/google-gax-0.20.0.tgz",
      "integrity": "sha512-JoaRCQtks60zuB3c5/5y60jG+xFBP67yYIgF6UuuDDVZtj/Z6kCKqjrGWNXEzFH2jolHZcvocST3JMwA/XClvA==",
      "requires": {
        "@grpc/grpc-js": "^0.2.0",
        "@grpc/proto-loader": "^0.3.0",
        "duplexify": "^3.6.0",
        "extend": "^3.0.1",
        "globby": "^8.0.1",
        "google-auth-library": "^2.0.0",
        "google-proto-files": "^0.16.0",
        "grpc": "^1.12.2",
        "is-stream-ended": "^0.1.4",
        "lodash": "^4.17.10",
        "protobufjs": "^6.8.8",
        "retry-request": "^4.0.0",
        "semver": "^5.5.1",
        "through2": "^2.0.3"
      }
    },
```

Error:

```
 error: {
    message: "13 INTERNAL: GOAWAY received"     
    stack: "Error: 13 INTERNAL: GOAWAY received
    at Object.exports.createStatusError (/service/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/service/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/service/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/service/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/service/node_modules/grpc/src/client_interceptors.js:845:24)"     
   }
```

**Comment by callmehiphop** [comment] 2019-02-04 20:57
I'm going to close this, because it looks like a duplicate of #27

**Closed by callmehiphop** 2019-02-04 20:57 UTC
Labels: :rotating_light:, priority: p1, type: bug
