### ISSUE TITLE
What type of PubSub message.data?

### ISSUE THREAD

**Issue by maidanskyi** [googleapis/nodejs-pubsub#524] opened 2019-03-05 12:25 UTC
Hi guys,
I'm using Google Pub/Sub on a project and I've a few problems,
here is one of then - **I'm pushing buffered data into the topic but I don't understand what I'm consuming.** Maybe, you can help me to understand where is a problem. According to Google docs for [0.23.x](https://cloud.google.com/nodejs/docs/reference/pubsub/0.23.x/google.pubsub.v1#.PubsubMessage) - `message.data` field has a string type(but as I see it's a Buffer)

#### Here is my code:
Publisher and consumer:
```typescript
import { PubSub } from '@google-cloud/pubsub'
import { Observable, fromEvent } from 'rxjs'
import { map, catchError } from 'rxjs/operators'

/**
 * Pub/Sub Service
 */
export class PubSubService implements IPubSubService {

  private pubsub = new PubSub()

  public async publish(topic_name: string, data: T): Promise<void> {

    try {

      const message = Buffer.from(JSON.stringify(data))

      const messageId = await this.pubsub
        .topic(topic_name)
        .publish(message)

      console.log(`Message ${messageId} published.`)

    } catch (err) {

      console.error('Publish error:', err)

    }

  }

  public consume(
    subscr_name: string
  ): Observable {

    return fromEvent(this.pubsub.subscription(subscr_name), 'message')
      .pipe(

        map(message => {

          const d = message.data.toString()
          console.log('HOT: d:', d)

          message.data = JSON.parse(d) // I just want to have parsed `data` field for next handlers

          console.log(`Received message ${message.id} cold`)
          return message

        }),

        catchError((err, caught) => {

          console.error('Consume error hot: ', err)

          return caught

        })

      )

  }
......
}
``` 

#### And here is my logs
![image](https://user-images.githubusercontent.com/12535712/53804318-e34dbe00-3f4f-11e9-80a9-7e60e2db0ed8.png)

`message.data` is a Buffer object.
As you can see, `message.data.toString()` frequently returns `string`, but sometimes it returns `object`. 

Hm... but why? What i'm doing wrong? The publish method always publish a valid JSON data.

#### Environment details

  - OS: Linux/Ubuntu
  - Docker image: node:10.5.0-alpine
  - Node.js version: 10.5.0
  - npm version: 6.5.0
  - `@google-cloud/pubsub` version: 0.26.0

Thanks!

**Comment by callmehiphop** [comment] 2019-03-05 17:35
Hi @maidanskyi, I'm not sure why that says string, because it definitely will **always** be a `Buffer`. The `[object Object]` is pretty unexpected, I think it could be 1 of 2 things (maybe):

1. `d` is **not** a Buffer or a string, but rather an object. This seems unlikely, but if that is the cause I'd say you've uncovered quite the bug in our library! I'll need your help to confirm if that is what is going on and what the contents of said object are.
1. There could have been a serialization mistake in your app where `toString()` was called instead of `JSON.stringify()` when publishing a message. This would cause the received message to essentially be `Buffer.from('[object Object]');`

@alexander-fenster I think the incorrect type comes from [generated docs](https://github.com/googleapis/nodejs-pubsub/blob/master/src/v1/doc/google/pubsub/v1/doc_pubsub.js#L78)? Is this something you can help with?

@JustinBeckwith Any ideas why docs haven't been pushed to cloud site since `0.23.0`? We're on `0.27.0` now. I was going to reference some of the later docs but noticed they aren't there 😱

**Comment by JustinBeckwith** [comment] 2019-03-05 18:11
Right now the doc publishing process is manual (fix for that coming soon).  @jkwlui can you turn the crank here?

**Comment by maidanskyi** [comment] 2019-03-06 11:12
Hi @callmehiphop, @JustinBeckwith 

@callmehiphop, the second case is not my, 100%!
I'm sending usual JSON (array with objects(values contain strings or numbers), nothing special). 
`few kb < message size < 2Mb`

**Comment by callmehiphop** [comment] 2019-03-06 17:47
@maidanskyi would you be able to put together a small reproduction of your issue? All our tests consistently show a `Buffer` being returned.

**Comment by maidanskyi** [comment] 2019-03-11 10:13
Hi, I was testing my code these few days and I found the next thing - the problem only arises when I modify the date field of the incoming message from `PubSub`. Otherwise, Buffer always comes.

**Comment by callmehiphop** [comment] 2019-03-11 10:33
@maidanskyi any chance you could share some code with us?

**Comment by maidanskyi** [comment] 2019-03-11 12:35
@callmehiphop I gave you an access to the repository

**Comment by callmehiphop** [comment] 2019-04-18 16:31
@maidanskyi I have to apologize, this kind of escaped me. I tried to review your code but I didn't find anything that might explain the results you're seeing. Are you still experiencing this issue?

**Comment by callmehiphop** [comment] 2019-04-30 15:54
Been kind of quiet here, I'm going to close this for now but if any new info becomes available let us know!

**Closed by callmehiphop** 2019-04-30 15:54 UTC
Labels: triaged for GA, type: question
