### ISSUE TITLE
Many ways to construct a Subscription without specifying message receipt options

### ISSUE THREAD

**Issue by jganetsk** [googleapis/nodejs-pubsub#247] opened 2018-09-07 22:01 UTC
The Subscription constructor takes an important options argument for configuring the receipt of messages: aka batching/flow control

https://cloud.google.com/nodejs/docs/reference/pubsub/0.19.x/Subscription#Subscription

But there are many ways to get a Subscription object without having the ability to specify these options:
https://cloud.google.com/nodejs/docs/reference/pubsub/0.19.x/v1.SubscriberClient#createSubscription (note these are a *different* set options that are required for the CreateSubscription call, but not for configuring the reciept of messages)
https://cloud.google.com/nodejs/docs/reference/pubsub/0.19.x/v1.SubscriberClient#getSubscription
https://cloud.google.com/nodejs/docs/reference/pubsub/0.19.x/v1.SubscriberClient#listSubscriptions

The Python library does this better... it decouples the Subscription as a noun from the verb of subscribing. Instead of taking these options in via constructor argument, a subscribe method is provided that takes these options: https://googlecloudplatform.github.io/google-cloud-python/latest/pubsub/subscriber/api/client.html#google.cloud.pubsub_v1.subscriber.client.Client.subscribe 

However, this can't work given the way things are currently structured in the Javascript library, because the Subscription object *is* an EventEmitter. Therefore, a Subscription cannot exist without being already configured to receive messages.  Alternately, you could make the Subscription object not be an EventEmitter, and (similar to Python) add a subscribe method that takes configuration and returns an EventEmitter.

**Comment by callmehiphop** [comment] 2018-09-20 16:43
This seems reasonable to me. @stephenplusplus @jmdobry do you have any feelings here?

**Comment by stephenplusplus** [comment] 2018-09-29 13:38
I would rather keep things the way they are, in that a `Subscription` is ready to emit messages whenever the user is. Another way we thought to solve this was adding a `setOptions()` (better name welcome): https://github.com/googleapis/nodejs-pubsub/issues/12

**Comment by callmehiphop** [comment] 2018-12-05 17:50
I'm going to close this since it appears to be a duplicate of #12

**Closed by callmehiphop** 2018-12-05 17:50 UTC
Labels: :rotating_light:, priority: p1, triaged for GA, type: bug
