### ISSUE TITLE
Typescript error `TS2305` while building a project with latest version (0.30.1)

### ISSUE THREAD

**Issue by xyclos** [googleapis/nodejs-pubsub#676] opened 2019-06-26 14:47 UTC
#### Environment details

  - OS: macos 10.14.5
  - Node.js version: 8.16.0
  - npm version: 6.4.1
  - `@google-cloud/pubsub` version: 0.30.1

#### Steps to reproduce

  1. Create a typescript project which depends on google-cloud/pubsub: ^0.30.1
  2. install deps and build with `tsc`

#### Output from tsc

```
node_modules/@google-cloud/pubsub/build/src/index.d.ts(75,10): error TS2305: Module '"../../../../@grpc/grpc-js/build/src"' has no exported member 'ServiceError'.
node_modules/@google-cloud/pubsub/build/src/message-queues.d.ts(18,20): error TS2305: Module '"../../../../@grpc/grpc-js/build/src"' has no exported member 'ServiceError'.
node_modules/@google-cloud/pubsub/build/src/message-stream.d.ts(17,20): error TS2305: Module '"../../../../@grpc/grpc-js/build/src"' has no exported member 'ServiceError'.
node_modules/@google-cloud/pubsub/build/src/message-stream.d.ts(17,42): error TS2305: Module '"../../../../@grpc/grpc-js/build/src"' has no exported member 'StatusObject'.
node_modules/@google-cloud/pubsub/build/src/pubsub.d.ts(19,10): error TS2305: Module '"../../../../@grpc/grpc-js/build/src"' has no exported member 'ServiceError'.
node_modules/@google-cloud/pubsub/build/src/pubsub.d.ts(19,24): error TS2305: Module '"../../../../@grpc/grpc-js/build/src"' has no exported member 'ChannelCredentials'.
```

#### Workaround

  - I rolled back to 0.29.1 and was able to build with `tsc` successfully.

I'm willing to contribute if someone might be able to point me into the correct direction to fix this.

Thanks!

**Comment by callmehiphop** [comment] 2019-07-01 13:45
@xyclos could you share your TypeScript version and `tsconfig.json` contents with us? I'm not able to reproduce this locally.

**Comment by xyclos** [comment] 2019-07-02 19:17
```
{
  "compilerOptions": {
    "resolveJsonModule": true,
    "allowSyntheticDefaultImports": true,
    "outDir": "./dist/",
    "noImplicitAny": true,
    "moduleResolution": "node",
    "module": "commonjs",
    "esModuleInterop": true,
    "target": "es6",
    "sourceMap": true,
    "baseUrl": ".",
    "paths": {
      "*": ["node_modules/*", "src/types/*"]
    }
  },
  "include": ["src/**/*"],
  "exclude": ["src/**/__tests__/**/*"]
}
```
`typescript : ^3.5.2`

**Comment by laljikanjareeya** [comment] 2019-09-03 15:32
@xyclos not able to reproduce with given configuration and version, could you try to delete `node_modules` and `package-lock.json` file and run `npm install`.

**Comment by callmehiphop** [comment] 2019-09-04 17:54
@xyclos is this still an issue for you?

**Comment by callmehiphop** [comment] 2019-09-11 13:43
There hasn't been much activity here in a little while, so I'm going to close this out. If anyone continues to experience this please let us know and we'll be happy to re-open and investigate!

**Closed by callmehiphop** 2019-09-11 13:43 UTC
Labels: needs more info, priority: p2, type: bug
