### ISSUE TITLE
SSL23_GET_SERVER_HELLO:unknown protocol behind proxy

### ISSUE THREAD

**Issue by steffiisawesome** [googleapis/nodejs-pubsub#133] opened 2018-05-28 10:29 UTC
#### Environment details

  - OS: CentOS Linux release 7.3.1611
  - Node.js version: v9.5.0
  - npm version: 5.6.0
  - `@google-cloud/pubsub` version: 0.18.0

#### Steps to reproduce

  1. 
```
const PubSub = require('@google-cloud/pubsub');

const config = {
    projectId: 'my-awesome-project',
    keyFilename: 'my-awesome-project-d8d7g557s8.json'
};
const topicName = 'product-connect-preprod';

let pubsub = new PubSub(config);
pubsub.createSubscription("interesting-topic", "subscriptionname")
    .then(data => {
        console.log(data);
    })
    .catch(err => {
        console.error(err);
    });
```
  2. env variables
```
http_proxy=http://proxy.host:8080
HTTP_PROXY=http://proxy.host:8080
https_proxy=http://proxy.host:8080
HTTPS_PROXY=http://proxy.host:8080
```

I try to subscribe to a Google PubSub topic behind a corporate http proxy and get the following error:

`
Auth error:Error: write EPROTO 139711176046400:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:
`

The proxy is available via http only, but must be used for all connections. You'll find the same error in various bug pools of other projects, but none of the mentioned workarounds seem to work here.

**Comment by danoscarmike** [comment] 2018-05-30 22:28
@steffiisawesome thanks for the logging the issue.  @stephenplusplus can you please take a look?

**Comment by stephenplusplus** [comment] 2018-07-24 23:07
This seems like a possible duplicate of https://github.com/googleapis/nodejs-storage/issues/277, in that proxy problems all lead to an issue in one dependency. Please follow along there for some discussion that might be useful.

**Comment by Matt11** [comment] 2018-11-06 14:54
@stephenplusplus - Now what is the solution to this issue? The possible duplicate you mentioned also doesn't help...

**Comment by stephenplusplus** [comment] 2018-11-12 20:08
@JustinBeckwith I believe you had been working on the Axios + Proxy issues-- do you know what became of that, and if your prior work would have fixed this?

**Comment by JustinBeckwith** [comment] 2018-12-03 16:21
Aye, that's where we're headed.

**Comment by mainephd** [comment] 2018-12-03 18:16
Is there anything i can help with? @JustinBeckwith

**Comment by stephenplusplus** [comment] 2019-04-29 21:20
I believe @ajaaym [found a solution](https://github.com/googleapis/nodejs-logging/issues/350#issuecomment-466108461):

> can you please try setting both env variable https_proxy & HTTPS_PROXY GRPC uses https_proxy and authentication which goes through normal node request uses HTTPS_PROXY.

**Closed by stephenplusplus** 2019-04-29 21:20 UTC
Labels: :rotating_light:, priority: p1, type: bug
