### ISSUE TITLE
'pause' not sent to underlying stream

### ISSUE THREAD

**Issue by dpcollins-google** [googleapis/nodejs-pubsub#573] opened 2019-04-16 21:29 UTC
The 'pause' method on the MessageStream class is not proxied to the underlying grpc PullStreams.  This means that messages continuously back up at the MessageStream layer without ever triggering grpc channel backpressure, causing infinite buildup irrespective of flow control settings.

**Comment by callmehiphop** [comment] 2019-04-17 00:21
@dpcollins-google the underlying grpc streams [get piped into the message stream](https://github.com/googleapis/nodejs-pubsub/blob/master/src/message-stream.ts#L212), so there shouldn't be a need to manually call pause/resume since streams have back pressuring built in.

Are you experiencing an issue where you see a message pile up or memory leak, etc.?

**Comment by dpcollins-google** [comment] 2019-04-18 21:40
I am experiencing a memory backup.  The subscriber code is [here](https://github.com/GoogleCloudPlatform/pubsub/blob/master/load-test-framework/node_src/src/subscriber_task.js).  When publishing with a message size of 9MB, my subscriber processes (one per core on a 16 core GCE machine with 60GB of ram) get killed by the OOM killer, even though I've set a flow control byte limit of 500 MB.

Even presuming that there are 16 messages per stream (80 per process) backed up in the GRPC layer as described [here](https://github.com/grpc/grpc-node/issues/123), this amounts to 1.2GB/core total, still not enough to account for the 60GB of ram.

There doesn't seem to be anywhere other than in the stream layer that these messages could be backing up, no references to them outlive the on('message') callback.

**Comment by callmehiphop** [comment] 2019-04-18 22:28
@dpcollins-google I think there are a few things worth mentioning 

* messages pass through grpc streams in batches, so I *think* they will be closer to 20MB per object
* we monkey patch grpc streams so there should never be more than 1 batch per grpc stream buffered on the JS side
* The C++ portion the grpc addon also buffers messages, however I don't have any insight into how many and I don't believe this is configurable

You might try testing the js version of gRPC which should buffer fewer messages.

**Comment by dpcollins-google** [comment] 2019-04-18 23:25
Given that I have a repeatable scenario that can trigger this, do you have any suggestions for how to determine in which of these layers the backup is?  Doing something other than the default client setup is a non-starter for me.

**Comment by dpcollins-google** [comment] 2019-04-19 13:26
I've attached a heap dump when 50/60 GB of memory was in use.  It doesn't look like the primary memory usage is inside of node, but perhaps someone who understands the library better could determine whether there is a leak of node managed grpc resources?  
[dump.heapsnapshot.zip](https://github.com/googleapis/nodejs-pubsub/files/3098254/dump.heapsnapshot.zip)

**Comment by sduskis** [comment] 2019-05-20 19:29
@ajaaym and @callmehiphop, can either of you summarize our current state on this?  Is this issue actionable?

**Comment by sduskis** [comment] 2019-05-21 13:30
I spoke with @ajaaym.  Basically, this issue comes down to some unknown issue in the node.js runtime relating to garbage collection.  We're having a tough time figuring out how to solve this one.

**Comment by sduskis** [comment] 2019-05-22 14:30
I spoke with @ajaaym again.  This was a problem with the way memory is shared between `grpc-c` and the node.js heap.  Node.js only has a reference to the data in messages until the data is used.  `grpc-c` will hold on to the memory until then, and Node.js will not be able to gc it, causing RSS to blow up.

`grpc-js` will be one way to solve this problem, since it will handle of the memory in the node.js heap.

@alexander-fenster and @bcoe, I think we need to move forward with `grpc-js` for this client pretty soon to fix this issue.

**Comment by sduskis** [comment] 2019-05-28 12:27
@dpcollins-google, this seems to be a duplicate of #627.  We have an environment variable we can use to replace the use of grpc-c with grpc-js.  @ajaaym or @callmehiphop, do you have instructions on how to use grpc-js right now?

**Comment by callmehiphop** [comment] 2019-05-28 15:13
@sduskis grpc-js comes enabled by default with google-gax@1.x. We just need to drop our direct dependency on grpc and update any references to grpc types to the appropriate grpc-js version.

**Comment by sduskis** [comment] 2019-06-07 15:38
I replaced the `type:bug` with `type:cleanup`.  This problem will occur in test conditions when the data in the message is not accessed.  That was a specific issue in the test process used by @dpcollins-google, since the test was not accessing the message, hence Node.js was not accounting for the memory allocation of the data.  To fix the memory issue, the test simply should access the data.

`grpc-js` would solve this issue once it's completely tested.  Upgrading to `grpc-js` is tracked in #627

**Closed** 2019-06-07 15:38 UTC
Labels: type: cleanup
