### ISSUE TITLE
Cannot update `ackDeadline` via `setOptions()`

### ISSUE THREAD

**Issue by WesCossick** [googleapis/nodejs-pubsub#1137] opened 2020-10-22 19:24 UTC
#### Environment details

  - OS: Distroless
  - Node.js version: v12
  - npm version: N/A
  - `@google-cloud/pubsub` version: 2.6.0

#### Steps to reproduce

1. Create a subscription by calling:

```ts
const subscription = topic.subscription('example-name', {
    ackDeadline: 300,
});

if (!(await subscription.exists())[0]) {
    await subscription.create({
        ackDeadlineSeconds: 300,
    });
}
```

2. Later, attempt to update the `ackDeadline` by calling:

```ts
const subscription = topic.subscription('example-name', {
    ackDeadline: 60,
});

subscription.setOptions({
    ackDeadline: 60,
});
```

3. See that in the Google Cloud Platform console, the deadline does not change:

<img width="668" alt="Screen Shot 2020-10-22 at 2 17 42 PM" src="https://user-images.githubusercontent.com/3850064/96919467-68615000-1471-11eb-9b8e-348b858640b0.png">

#### Other notes

The `.setMetadata()` call works just fine, at least with `retryPolicy` values.

**Comment by feywind** [comment] 2020-10-23 21:44
@WesCossick Thanks for the report. There was some discussion the other day, actually, about how the Node libraries for Pub/Sub sort of confuse the options for local library code, and the options passed on to the service. This might be an example of that. There is some intent to make this clearer, but that's probably going to be a bit. I'll put this on my list to look at, and maybe if there's not a bug there, we can at least make the usage clearer. (And if there is, I can work on a fix.)

**Comment by WesCossick** [comment] 2020-10-26 13:35
I agree that this library often intermingles local and cloud configuration settings in a way that can be confusing. In this case, though, I'm pretty sure `ackDeadline` is an option passed on to the Pub/Sub service. Whatever the option is _first_ set to is what is displayed in the Google Cloud Platform console. Attempts to later change that value never update what's displayed in the console, unless the subscription is deleted and recreated.

**Comment by laljikanjareeya** [comment] 2020-10-27 09:25
@WesCossick `setOptions` function will set the `ackDeadline` locally for specific request it doesn't update the actual `ackDeadline` saved in cloud.

Here is the [Issue](https://github.com/googleapis/nodejs-pubsub/issues/6) where user want to specify the `ackDeadline` for time being.

To update the `ackDeadline` you don't need to delete and recreate the subscription you can use `setMetadata` to update it. 

```ts
await subscription.setMetadata({
    ackDeadlineSeconds: 60
});
```

**Comment by feywind** [comment] 2020-10-27 23:08
@laljikanjareeya Thanks for that. It does sound like the right answer to me, upon second glance.

I do think there's definitely room for improvement in the method names and docs around options vs metadata.

**Comment by laljikanjareeya** [comment] 2020-10-28 09:01
@feywind definitely we need to improve the documentation on `setOptions`  I will make PR shortly, `setMetadata` method is consistent across the all library.

**Comment by WesCossick** [comment] 2020-10-28 17:08
@laljikanjareeya When you say "locally for specific request," what do you mean by that? How does that affect the behavior differently than the cloud setting?

Also, `ackDeadlineSeconds` is not a valid property for `.setMetadata()`. At least not according to TypeScript:

```
Object literal may only specify known properties, and 'ackDeadline' does not exist in type 'SubscriptionMetadata'.
```

**Comment by laljikanjareeya** [comment] 2020-10-30 10:05
I was trying to explain that if you have created two instance and you are setting `ackDeadline` using `setOption` to one of them subscription will not affect to second one.

```ts
 const subscription1 = topic.subscription('example-name')
 const subscription2 = topic.subscription('example-name')

subscription1.setOptions({
    ackDeadline: 60,
});
```
In above example `subscription2` will use the `ackDeadline` that has been set on console.

**Comment by feywind** [comment] 2022-02-16 21:41
After a discussion we had today about this, I think I have a better idea what's going on here, and we're going to try to improve it in the future. There's a client-side ack deadline and a separate server-side concept that is called the same thing. The client side one is used for determining how long to modAck, and the client apparently tells the server to change its value as part of that. So it's possible the updated value from `setMetadata` is simply being overwritten again by the client.

All of which is to say that this is probably more complicated than it looks at first glance, and it's something that's (hopefully) going to get fixed with a future revision of the client library APIs.

**Comment by feywind** [comment] 2022-02-16 21:41
@kamalaboulhosn I'm probably explaining this poorly :D Feel free to throw in any clarification for that comment.

**Comment by feywind** [comment] 2023-04-03 19:07
Ping, this is still on the radar.

**Comment by kamalaboulhosn** [comment] 2023-06-20 18:17
`setMetadata` is the correct method to use.

**Closed by kamalaboulhosn** 2023-06-20 18:17 UTC
Labels: type: docs, api: pubsub, priority: p3
