### ISSUE TITLE
Promises never throw or resolve if PUBSUB_EMULATOR_HOST is set to an invalid value

### ISSUE THREAD

**Issue by Gusten** [googleapis/nodejs-pubsub#339] opened 2018-11-16 10:39 UTC
#### Description
If the PUBSUB_EMULATOR_HOST env variable is set and is not a valid value, the pubsub client promises will never resolve or throw.

#### Environment details

  - OS: macOS 10.14.1
  - Node.js version: 10.13.0
  - npm version: 6.4.1 
  - `@google-cloud/pubsub` version: 0.21.1

#### Steps to reproduce

  1. export PUBSUB_EMULATOR_HOST=something
  2. run the following js snippet
```javascript
const { PubSub } = require("@google-cloud/pubsub");

async function start() {
  const pubsubClient = new PubSub({ projectId: "my-project-id" });

  try {
    const [topics] = await pubsubClient.getTopics();
    console.log(topics);
  } catch (error) {
    console.error(error);
  }
}
start().catch(console.error);
```

**Comment by callmehiphop** [comment] 2018-12-03 15:52
Possibly related to https://github.com/googleapis/gax-nodejs/issues/208

**Comment by watchinharrison** [comment] 2019-01-10 09:49
I'm seeing this issue when the value is set correctly but is running with jest, I'm using the pubsub emulator with docker so it's running in it's own container with an exposed port. The host name and port can be connected to from inside the testing container with bash. But doesn't appear to resolve when going through PubSub within the running test. 


1. Can confirm connecting to the emulator works in the usual container when running the app normally.
1. The test container is communicating with a mysql container fine.

**Comment by callmehiphop** [comment] 2019-01-16 15:16
I'm going to close this as a duplicate of googleapis/gax-nodejs#208

**Closed by callmehiphop** 2019-01-16 15:16 UTC
Labels: priority: p2, type: bug

**Comment by alanmynah** [comment] 2021-07-16 10:53
Would it be possible to at least add a warning to the client? Looks like googleapis/gax-nodejs#208 is a won't fix, so maybe we can save some time to other folk if just log a warning.
