### ISSUE TITLE
lint/docs tests appear to be breaking

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-pubsub#645] opened 2019-06-07 14:38 UTC
See:

https://github.com/googleapis/nodejs-pubsub/pull/641
https://github.com/googleapis/nodejs-pubsub/pull/639

It would be good to get these PRs green, so that we can star working through the backlog of open issues.

**Comment by sduskis** [comment] 2019-06-07 14:40
@bcoe, my understanding is that "type: bug" is for customer issues, which is why I changed the category.  This is definitely a problem, and needs to be fixed.  We'll work on them

**Comment by JustinBeckwith** [comment] 2019-06-07 15:58
👋 Regardless, master being broken is a P1 in my book.   We should address this today.

**Comment by callmehiphop** [comment] 2019-06-07 17:17
I believe this is a duplicate of #642

**Comment by callmehiphop** [comment] 2019-06-07 17:17
Quick fix is to just update the regex in synth.py

**Closed** 2019-06-07 17:45 UTC
Labels: priority: p1, type: process
