### ISSUE TITLE
Internal Server Error 500 / Fatal error: Trait 'description' not found...

### ISSUE THREAD

**Issue by caioricciuti** [googleapis/nodejs-pubsub#1525] opened 2022-04-19 13:26 UTC
Hello All, I send messages from by backend using pub/sub. Today out of nowhere I got the following error: 

Code: 500
Level: 0 
Status: "Internal server Error"
text: "Fatal error: Trait 'description' not found"

Anyone is having this issue? Thank you all in advance!

**Comment by meredithslota** [comment] 2022-10-27 16:43
Can you share any additional repro information? I took a look through the history of service issues, and it's possible this was caused by an internal issue that has since been resolved. Is this still occurring?

**Comment by feywind** [comment] 2022-12-22 23:09
Having not heard anything new, I'm going to go ahead and close this, feel free to comment if it's needed.

**Closed by feywind** 2022-12-22 23:09 UTC
Labels: type: question, api: pubsub, priority: p3
