### ISSUE TITLE
Update config for existing subscription

### ISSUE THREAD

**Issue by ForbesLindesay** [googleapis/nodejs-pubsub#1223] opened 2021-03-08 11:23 UTC
I want to manage Pub/Sub subscriptions automatically using the node.js API. Unfortunately, most properties of the subscription cannot be edited after it has been created. Specifialy, I want to be able to update:

- `ackDeadlineSeconds`
- `retryPolicy`

Both of these can be updated via the console UI or via the gcloud CLI, but it is frustrating that I have to abandon the simple, type safe world of node.js just to make these simple changes.

**Comment by feywind** [comment] 2021-03-15 07:40
@ForbesLindesay Thanks for the report. I think the expectation was that most people would use the CLI or web site to update those kinds of settings, but it does seem like it'd be a nice gap to close.

**Comment by feywind** [comment] 2021-03-22 20:46
Turns out this is just a piece that didn't end up getting implemented earlier, so I'm switching it to be a bug.

**Comment by govindrai** [comment] 2021-05-28 22:22
@ForbesLindesay With the latest library, You can use `topic(topicName).subscription(subscriptionName).setMetadata({...updates})` to update those values. Official Example [here](https://github.com/googleapis/nodejs-pubsub/blob/master/samples/updateDeadLetterPolicy.js). 

@feywind my 2 cents, this is poor name for a method that update a subscription. A better name would've been simply updateSubscription. Surprisingly there is also a Subscriber#updateSubscription and SubscriberClient#updateSubscription that accomplishes the same. Too many ways to do the same thing... very confusing docs due to too much internal api details exposed.

**Comment by feywind** [comment] 2021-05-31 20:55
@hongalex @kamalaboulhosn Maybe this is something we should add to the list of stuff to look at with future API updates across languages? I do agree `setMetadata` is kind of unobvious for this.

The reason there are those two `updateSubscription` methods, by the by, is that the `SubscriberClient` is the "raw" generated (gapic) library. The other one (`Subscriber`) is an old veneer layer (all handwritten) that was ported to the newer gapic layer. It's also pseudo-private; the intended method would've been the `setMetadata` up top.

I do think the veneer code is due for some updating, we're just trying to avoid causing too much disruption to everyone. There's been talk of having a new "clean" API that is up to date and more in line with the other libraries, and then just have an "old" API that plugs into that. But that's not work that's been scheduled or anything yet.

Anyway, I do appreciate the feedback!

**Comment by kamalaboulhosn** [comment] 2021-06-08 14:10
I haven't seen `setMetadata` as a method in any of the other client libraries and I agree that it is not obvious. Was that something auto-generated that is consistent across other node.js libraries?

**Comment by feywind** [comment] 2021-09-09 16:24
I'm going to flip this over to feature request, as I think the issue is not that it's impossible, but that the API is a bit less discoverable than we'd like.

**Comment by feywind** [comment] 2022-03-24 19:29
I'm moving this into the API v2 discussion internal doc, I think that's where we'll end up fixing it.

**Closed by feywind** 2022-03-24 19:29 UTC
Labels: type: feature request, api: pubsub
