### ISSUE TITLE
No error returned for invalid private_key

### ISSUE THREAD

**Issue by ibmappcon** [googleapis/nodejs-pubsub#1063] opened 2020-07-21 10:04 UTC
Hi, 

We are using nodejs-pubsub package v2.2.0 for one of our connector and it was observed that the endpoint does not return any error when the client is created with invalid private_key. Also, when this client was used to get topics, it did not return autentication error. However, after waiting for the default timeout, it returned an error with code 4 as below:

```
{ Error: Total timeout of API google.pubsub.v1.Publisher exceeded 600000 milliseconds before any response was received.
    at repeat (C:\Users\Ms\Documents\Connectors\GooglePubSub\poc_scripts\node_modules\google-gax\build\src\normalCalls\retries.js:66:31)
    at Timeout.setTimeout [as _onTimeout] (C:\Users\Ms\Documents\Connectors\GooglePubSub\poc_scripts\node_modules\google-gax\build\src\normalCalls\retries.js:101:25)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10) code: 4 }
```

We expect authentication error in the above error case. Could you please help in understanding how to get correct error in such case.

**Comment by feywind** [comment] 2020-07-21 21:07
Hi, @ibmappcon - thanks for adding a report for this. I haven't heard of it before. Asking for a few clarifications:

- What's causing the invalid private key error specifically? (Meaning, the private key was pasted incorrectly but the username is correct, or something like that?)

- Can you paste some really simplified code that shows what you're calling in your connector? e.g.:

```
const pubsub = new PubSub();
await pubsub.getTopics();
```

Thanks!

**Comment by ibmappcon** [comment] 2020-07-22 04:26
@feywind Please refer the script below:
```
const pubsub = new PubSub({
  client_email: 'Valid_email',
  private_key: 'Invalid_private_key'
},
projectId: 'valid_ID')

pubsub.getTopics({ 
  pageSize: 1
}, (err, topics, nextPageToken)=>{
  console.log('err', err)
  console.log('response', topics)
})
```

**Comment by laljikanjareeya** [comment] 2020-07-22 10:12
@ibmappcon below is right way to pass the `client_email` and `private_key`:

```ts
const pubsub = new PubSub({
    credentials: {
        client_email: 'email,
        private_key: 'private key'
    },
    projectId: 'project-id'
});
```
Make sure your private_key should be in following format:
```
-----BEGIN PRIVATE KEY-----\n{REDACTED}\n-----END PRIVATE KEY-----\n
```

**Comment by ibmappcon** [comment] 2020-07-23 03:47
@laljikanjareeya Sorry for the above miss, updated the script. I had created new client in the same manner, still it failed to give error.

**Comment by laljikanjareeya** [comment] 2020-07-23 04:28
@ibmappcon  it it same error that you were getting previously?.

I debug it and It gives below error definitely not timeout error:
```
Error: 400 undefined: Getting metadata from plugin failed with error: invalid_grant: Invalid JWT Signature.
```

**Comment by ibmappcon** [comment] 2020-07-23 07:22
@laljikanjareeya yes, still getting the timeout error. Wondering if we need any extra configuration to obtain this error.

**Comment by ibmappcon** [comment] 2020-07-23 13:14
@laljikanjareeya we also observed that, for the latest node version, the endpoint gives proper error messages for invalid private key. However due to some constraints we need to use pubsub with node v10 in our application.

Can you suggest any work around for this?

**Comment by ibmappcon** [comment] 2020-07-24 07:33
@feywind any update on the issue? Can you suggest some workaround on this issue for node v10?

**Comment by laljikanjareeya** [comment] 2020-07-24 08:24
@ibmappcon  I have already tried with above given version but looks like it working fine, Here is the details:

Node: V10.16.3
npm: 6.9.0
@google-cloud/pubsub: "^2.2.0"

**Code snippet:**
```ts
import { PubSub } from '@google-cloud/pubsub';
const config = require('F:\\Keys\\key.json');

async function getTopics() {
    const pubsub = new PubSub({
        credentials: {
            client_email: config.client_email,
            private_key: config.private_key
        }, projectId: 'my-project-id'
    });

    pubsub.getTopics({
        pageSize: 1
    }, (err, topics, next) => {
        console.log(err);
    });
}

getTopics().catch(console.error);
```

**Output:**
```
{ Error: 400 undefined: Getting metadata from plugin failed with error: invalid_grant: Invalid JWT Signature.
    at Object.callErrorFromStatus (F:\common-test\pubsub-demo\node_modules\@grpc\grpc-js\build\src\call.js:31:26)
    at Object.onReceiveStatus (F:\common-test\pubsub-demo\node_modules\@grpc\grpc-js\build\src\client.js:176:52)
    at Object.onReceiveStatus (F:\common-test\pubsub-demo\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:342:141)
    at Object.onReceiveStatus (F:\common-test\pubsub-demo\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:305:181)
    at Http2CallStream.outputStatus (F:\common-test\pubsub-demo\node_modules\@grpc\grpc-js\build\src\call-stream.js:117:74)
    at Http2CallStream.maybeOutputStatus (F:\common-test\pubsub-demo\node_modules\@grpc\grpc-js\build\src\call-stream.js:156:22)
    at Http2CallStream.endCall (F:\common-test\pubsub-demo\node_modules\@grpc\grpc-js\build\src\call-stream.js:142:18)
    at Http2CallStream.cancelWithStatus (F:\common-test\pubsub-demo\node_modules\@grpc\grpc-js\build\src\call-stream.js:467:14)
    at callStream.filterStack.sendMetadata.then (F:\common-test\pubsub-demo\node_modules\@grpc\grpc-js\build\src\channel.js:226:36)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: '400',
  details:
   'Getting metadata from plugin failed with error: invalid_grant: Invalid JWT Signature.',
  metadata: Metadata { internalRepr: Map {}, options: {} },
  note:
   'Exception occurred in retry method that was not classified as transient' }
```

It seems like your key is valid but timeout from back-end, can you try again cleaning up the `node_modules` and changing your key as invalid.

**Comment by ibmappcon** [comment] 2020-07-25 07:52
@laljikanjareeya Thanks for the update!

We tried the exact same code with same node & npm version, and still see the same issue. We even tried this on three different machines to rule out the caching possibility, same behavior is observed.

**Comment by ibmappcon** [comment] 2020-07-28 06:00
@feywind @laljikanjareeya Any update on this issue?

**Comment by feywind** [comment] 2020-12-14 20:44
I just tried this myself, and I'm able to reproduce it with Node 10. It looks like something is having issues in the `node-jsonwebtoken` package. It's getting this error: https://github.com/auth0/node-jsonwebtoken/issues/642

Of course the answer is "fix your PEM file" 🙄 but there is something in gax that isn't properly dealing with that error. I wonder why it would've changed in Node 12 though.

**Comment by feywind** [comment] 2021-02-12 21:41
I got some more time to dig into this, and the unsatisfying explanation is that Node changed what it returns between Node 10 and Node 12 when failing to make a private key in the 'crypto' module. The actual interface (as far as exceptions go) isn't specified in the docs, so I guess they technically didn't break anything.

Latest Node unit test about this: https://github.com/nodejs/node-auto-test/blob/9cf2037cf5eed0e2bafda94e8facaa83e1283767/test/parallel/test-crypto-key-objects.js#L205

I don't know a lot about Node core, but it seems like the actual error must be coming from a change down in the C++ code, and was introduced between Node 10 and 12.

grpc-js seems to be assuming that it will get a numeric error code back when initializing from a key string, because `retry.retryCodes` is an array with three numbers in it.

```
                if (retry.retryCodes.indexOf(err.code) < 0) {
```

Node 10 seems to pass back `2` for the `err.code` here, which is interpreted as `UNKNOWN` and thus retried somewhat indefinitely.

In Node 12, it's receiving a _string_ for `err.code`: `ERR_OSSL_PEM_NO_START_LINE`. This is not being handled truly correctly either (imo), because grpc-js is simply not finding that code on the retryable error list, and it bails with an error.

So I think the unsatisfying answer here is just to do with Node does down in its internals for now, and basically validate that it looks like a key file before trying:

```
-----BEGIN PRIVATE KEY-----
```

I suspect the answer farther down the stack is going to be "this goes away in Node 12 and isn't problem for many users, so we will not fix it". Which is not very satisfying, I know. :| But probably the simplest thing is to try to do some basic validation on the key before it's passed in.

@murgatroid99 might have more insight on this than me, I'm still not super familiar with grpc-js' internals, but I'm going to close it pending further comment from others.

**Closed by feywind** 2021-02-12 21:41 UTC
Labels: :rotating_light:, api: pubsub, priority: p2, type: bug

**Comment by feywind** [comment] 2021-02-17 17:37
@ibmappcon If you've still got this problem, try pulling in the latest grpc-js (1.2.8). I haven't tested my repro again locally yet, but the auth errors should now correctly funnel into a non-retryable code.
