### ISSUE TITLE
Using sinon fakeTimers causes .publish() timeout

### ISSUE THREAD

**Issue by coldice** [googleapis/nodejs-pubsub#1160] opened 2020-11-27 22:17 UTC
- Node.js version: 14.15.0
- npm version: 6.14.8
- `@google-cloud/pubsub` version: 2.6.0

When using [sinon fakeTimers ](https://github.com/sinonjs/fake-timers) in tests, setting up a fake clock causes the `topic.publish()` function to timeout. This is probably not a problem with the pubsub client itself but some dependent timing library or sinon's fakeTimers itself.

It's worth noting that we were using fakeTimers in a different test file, setup like this: `clock = sinon.useFakeTimers(new Date());` which was actually not correctly reset, it appears this clock change has leaked over to a totally seperate test file where we are using pubsub. The same issue is also observed when calling `useFakeTimers` in the same file where pubsub is used, in which case `.publish()` just never returns.

**Comment by feywind** [comment] 2020-12-03 18:36
@coldice Thanks for the report! That's pretty interesting, can you post a small bit of code that causes it?

**Comment by feywind** [comment] 2021-06-01 18:22
I'm going to move this over to `feature request` since it seems like the problem is compatibility with sinon for this type of testing.

**Comment by feywind** [comment] 2022-03-24 19:18
I'm closing this out as part of cleanup, it seems like there's not a lot of interest to fix it right now.

**Closed by feywind** 2022-03-24 19:18 UTC
Labels: type: feature request, api: pubsub
