### ISSUE TITLE
Unexpected behaviour when using nodejs-pubsub to load balance message to subscribers

### ISSUE THREAD

**Issue by nicolasguenther** [googleapis/nodejs-pubsub#801] opened 2019-10-25 11:35 UTC
#### Environment details

  - OS: Windows
  - Node.js version: 10.15.3
  - npm version: 6.11.3
  - `@google-cloud/pubsub` version: 0.31.0

I want multiple subscribers to process messages one message at a time. From my understanding this can be achieved by using the following settings:

```  
const subscription = pubsub.subscription(subscriptionId, {
    flowControl: {
      allowExcessMessages: false,
      maxMessages: 1
    },
    streamingOptions: {
      maxStreams: 1
    }
  });
```

Based on the current unacked message count further subscribers will be started/stopped to reduce overall processing time.

In case the subscription has more unacked messages than currently running subscribers i would expect any newly started subscriber to instantly pickup a message and start processing. 

Instead my observation is that a newly started subscriber will never pickup a preexisting unacked message except in a situation where no subscriber was running. It seems as the previous running subscribers are putting a hold on messages even though they are not currently processing them. I think my above settings should prevent from such behaviour.

In contrast my load balancing scenario works fine if i start multiple subscribers and add multiple messages to the topic afterwards.

**Comment by callmehiphop** [comment] 2019-10-25 18:22
I think I have an idea of what is happening here. The configuration you've shared is indeed the only way to process a single message at a time, however it should be noted that PubSub doesn't actually let us configure the number of messages to send down at any given time.

I think what is happening is you are receiving a batch of messages (could be in the hundreds) and we give you the desired amount (in this case 1) while we continuously extend the ack deadline for any others until you're ready for them. This essentially puts a lock on these messages and prevents them from being redelivered. 

You could try setting the flow control [`maxExtension`](https://googleapis.dev/nodejs/pubsub/latest/global.html#FlowControlOptions) option to 0, although this will result in a frequent redeliveries if you have a short ack deadline.

**Comment by nicolasguenther** [comment] 2019-11-01 12:53
In my use case processing a single message can take multiple (up to ~20) minutes. I tried various scenarios to validate your guess. I'll try to illustrate it with an example where messages are published one by one to prevent batches of multiple messages:

- start subscriber A
- publish message 1
-> subscriber A processes message 1
- publish message 2
-> subscriber A still processes message 1, message handler not called for message 2
- start subscriber B while message 1 is still processed by subscriber A

I would expect subscriber B to immediately pickup message 2. Instead subscriber A finishes processing message 1 and afterwards picks up message 2. It looks like subscriber A put a lock on message 2, which from my understanding should not happen using my above configuration.

I tried the same scenario with `maxExtension: 0`. This seems to prevent from extending the ack deadline of message 1 while it is being processed. While i would like to have the "queued" or locked messages to be redelivered i need the ack deadline for the currently processed message to be extended as long as processing finishes or fails (in this case .nack() would be called).

**Comment by callmehiphop** [comment] 2019-11-02 04:45
@nicolasguenther by any chance are you creating (not starting) subscriber B after message 2 is published?

**Comment by nicolasguenther** [comment] 2019-11-02 09:41
I create and start subscriber B after message 2 is published. I would expect subscriber B to immediately pickup message 2 when started.

**Comment by callmehiphop** [comment] 2019-11-04 17:27
@nicolasguenther I had to do a double check on the [subscriber docs](https://cloud.google.com/pubsub/docs/subscriber), but it sounds like what you're seeing is happening by design.

> A message published before a given subscription was created will usually not be delivered for that subscription. Thus, a message published to a topic that has no subscription will not be delivered to any subscriber.

**Comment by nicolasguenther** [comment] 2019-11-04 20:33
Thanks for pointing this out. I think it is crucial to distinguish between the terms subscription and subscriber. I'm using a single subscription with multiple subscribers as described in the same document:
> Multiple subscribers can make pull calls to the same "shared" subscription. Each subscriber will receive a subset of the messages.

My subscription was created before any message was published. My subscriber B (the node program using nodejs-pubsub) in the above scenario was indeed started after message 2 was published. 

When i publish a message with no running subscribers and start a subscriber afterwards, the message is delivered to the subscriber, Interestingly enough.

**Comment by callmehiphop** [comment] 2019-11-04 20:47
@nicolasguenther Thanks for clarifying and sharing all these details about your application. I think you may want to consider using the [pull](https://github.com/googleapis/nodejs-pubsub/blob/master/samples/subscriptions.js#L273) API.

Since your application only wants to process 1 message at a time and it can take a bit of time, it seems like the streaming API doesn't offer you very many advantages, especially since we can't control which streams/subscribers messages are actually delivered to. Using the pull API you can specify the exact amount, so any subsequent messages won't get locked in a subscriber you don't want them in. 

WDYT?

**Comment by nicolasguenther** [comment] 2019-11-04 21:21
Thanks again. I think obtaining a subscription with `pubsub.subscription()` (as i did) is implicitly using the pull API as described in  [Subscription Docs](https://googleapis.dev/nodejs/pubsub/latest/Subscription.html):

>The subscription will pull for messages automatically as long as there is at least one listener assigned for the message event. By default Subscription objects allow you to process 100 messages at the same time. You can fine tune this value by adjusting the options.flowControl.maxMessages option.

I still don't understand why using this with the above flow control settings and streaming options doesn't behave as expected. I see that using `pubsub.v1.SubscriberClient()` like in the example you linked could give me more fine-grained control, though. So i'll give it a try in the next days.

**Comment by callmehiphop** [comment] 2019-11-05 20:28
@nicolasguenther so we offer 2 clients, a handwritten one (`pubsub.subscription()`) and a generated client (`pubsub.v1.SubscriberClient`). We don't actually use or support the `pull` RPC in our handwritten client (which you appear to be using), we use a streaming version instead. 

It is pretty reasonable to expect messages to stop being delivered to your subscriber once you've hit the configured limit, but currently grpc (our transport library) doesn't actually let us stop the flow of data until an unconfigurable buffer is filled. So what ends up happening is we just manage those messages behind the scenes until you're ready for them.

**Comment by feywind** [comment] 2020-05-05 17:21
There hasn't been a response on this for a while, so I'm going to go ahead and close it, but please feel free to re-open and/or comment further if there is still a problem.

**Closed by feywind** 2020-05-05 17:21 UTC
Labels: api: pubsub, type: question
