### ISSUE TITLE
Possible Memory Leak Issue with NodeJs PubSub Client, when publishing messages to topic

### ISSUE THREAD

**Issue by madhu-ggl** [googleapis/nodejs-pubsub#758] opened 2019-09-25 08:27 UTC
Raising this issue here, as the customer is deeply impacted and raised a P1 issue on buganiser and could not find a resolution. Help needed to resolve this urgently.

I am trying to run a node js job to read data from dynamo db and send to PubSub.

I am running this job in praveen-workspace (https://console.cloud.google.com/compute/instancesDetail/zones/asia-south1-c/instances/praveen-workspace?project=maximal-furnace-783&tab=details&duration=PT6H)

You can see the following chart to get the memory information when the job is run.

https://app.google.stackdriver.com/dashboards/2645945472340513163?project=maximal-furnace-783

I am using PubSub client `https://github.com/googleapis/nodejs-pubsub` as mentioned here. 
pubsub version:
"@google-cloud/pubsub": "0.30.1", 
node -v : v10.16.3
npm -v: 6.9.0

I tried with the latest version 1.0.0 too, but it still gives the same error.

Please let me know whether some other information should be provided.

**Comment by callmehiphop** [comment] 2019-09-25 15:19
Hi @madhu-ggl, this sounds like a duplicate of https://github.com/googleapis/nodejs-pubsub/issues/757. Could you try deleting any lock files and re-installing your dependencies?

**Comment by callmehiphop** [comment] 2019-09-27 16:29
We have since made a release containing a fix on the gRPC side, so I'm going to close this out. If your issue continues to occur, please let us know. Thanks!

**Closed by callmehiphop** 2019-09-27 16:29 UTC
Labels: priority: p2, status: duplicate, type: bug
