### ISSUE TITLE
modifyAckDeadline is duplicating messages

### ISSUE THREAD

**Issue by JamesTheTerry** [googleapis/nodejs-pubsub#124] opened 2018-05-02 00:06 UTC
#### Environment details

  - OS: macOS 10.13.4 (High Sierra)
  - Node.js version: 9.11.1
  - npm version: 5.6.0
  - `@google-cloud/pubsub` version: 0.18.0

#### Steps to reproduce

  1. Create a subscriber and topic
  2. Send a message to the topic
  3. Use v1's pull method
  4. modifyAckDeadline of a single message
  5. ack said message a couple seconds later

I'm using Pub/Sub for processes that normally take a couple minutes, but can sometimes extend to 30+ mins. Here's a second by second look at what my little test setup does.

0:00 - pulldown 1 message from subscription with 20 second deadline (or 600 seconds, same result)
0:05 - modifyAckDeadline by 20 seconds
0:15 - ack message; then pull down the same message from the queue

I decided to try this with two instances pulling down messages. After sending one message, as soon as I would modifyAckDeadline on the instance that got the message, the other instance would pull down the message and start the same process.

Eventually, an ack finally sticks and the message goes away.

So it seems that modifyAckDeadline is creating a duplicate message.

**Comment by stephenplusplus** [comment] 2018-05-02 14:35
@callmehiphop -- I believe this is a common report. Do we have an issue or PR that would cover this already? Or is this part of the redesign we're about to go through?

**Comment by callmehiphop** [comment] 2018-05-02 15:43
@stephenplusplus I could be wrong, but it sounds like he's using the autogen layer. We don't allow users to use pull or modack within the hand written client.

@JamesTheTerry can you confirm that you're using the autogen layer?

**Comment by JamesTheTerry** [comment] 2018-05-02 17:16
@callmehiphop Forgive me, what is the autogen layer? I'm using the v1.SubscriberClient if that helps.

**Comment by callmehiphop** [comment] 2018-05-02 17:36
My apologies for not clarifying. We offer 2 different clients - one of which is auto generated and offers bare bones functionality, the other is hand written (on top of the autogen) with some convenience methods/etc. Typically anything with the version prefix/namespace is a reference to the autogen.

@kir-titievsky any idea why we might be seeing re-deliveries here? Could this be a side effect of the pull method? Would receipting the messages prevent a redelivery?

**Comment by JamesTheTerry** [comment] 2018-05-30 22:28
@danoscarmike I stopped using it and built a small load balancer instead, which works out better for me given that my tasks take like an hour sometimes.

**Comment by TraxRetail** [comment] 2018-12-16 07:40
I can confirm the issue: @google-cloud/pubsub 0.22.2 (consitst to a few lower version)
nodejs 8.12.0
npm 6.5.0
linux mint 17.3
I'm having the same issue with retrieving message before the lock is over, this is out test in nodejs:
```
const cp = CloudProvider({type: GCP, env: 'INT'});
            const rand = Math.random().toString(16);
            await cp.queue.sendMessage(GCP_TOPIC_QUEUE, {test: rand});

            const messages = await cp.queue.receiveMessage(GCP_QUEUE, {maxMessages: 10, waitTimeout: 2});
            const message = messages.find(m => m.data.test === rand);

            // Retrieving the message
            assert.ok(message);

            await cp.queue.extendMessageLock(GCP_QUEUE, message, {lockTimeout: 400});
            await delay(360000);
            const messages2 = await cp.queue.receiveMessage(GCP_QUEUE, {
                maxMessages: 10,
                waitTimeout: 2
            });
            const message2 = messages2.find(m => m.data.test === rand);

            // Message should not be not be here, but is retrieved (it usually don't work but sometimes it
            // does)
            assert.ok(!message2);
            // wait for the lock to be done
            await delay(50000);

            const messages3 = await cp.queue.receiveMessage(GCP_QUEUE, {maxMessages: 10, waitTimeout: 2});
            const message3 = messages3.find(m => m.data.test === rand);

            // Message should be here because `extendMessageLock` is over
            assert.ok(message3);
```
extendMessageLock function
```
async function extendMessageLock(queue, message, options = {}) {
        const client = new pubSubHelper.v1.SubscriberClient({});
        const subscription = client.subscriptionPath(GCP_PROJECT_ID, queue);
        const ackDeadlineSeconds = isFinite(options.lockTimeout) ? options.lockTimeout : MESSAGE_LOCK_TIMEOUT;
        const ids = messagesToIdArray(message);

        return await client.modifyAckDeadline({subscription, ackIds: ids, ackDeadlineSeconds});
    }
```

**Comment by callmehiphop** [comment] 2019-01-16 15:31
I'm going to close this issue since it appears to be an API issue and not a client issue.

**Closed by callmehiphop** 2019-01-16 15:31 UTC
Labels: :rotating_light:, priority: p2, type: question

**Comment by jeffijoe** [comment] 2020-07-02 18:02
I'm seeing this as well. By not doing `modifyAckDeadline` no duplicate is generated.

Do we even need to use this in userland? I believe I read somewhere that the convenience client will keep extending for you?
