### ISSUE TITLE
Documentation on how to use native gRPC doesn't type check

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [googleapis/nodejs-pubsub#1268] opened 2021-04-23 16:44 UTC
#### Environment details

  - OS: Linux
  - Node.js version: 12.20.1
  - npm version: 6.14.10
  - `@google-cloud/pubsub` version: 2.11.0

#### Steps to reproduce

  1. `cd $(mktemp -d)`
  2. `npm i @google-cloud/pubsub grpc typescript`
  3. create `try.ts`:
```typescript
import grpc = require('grpc');
import {PubSub} from '@google-cloud/pubsub';

new PubSub({grpc});
```
  4. `npx tsc try.ts`
  5. compilation fails

```
try.ts:4:13 - error TS2739: Type 'typeof import("grpc")' is missing the following properties from type 'typeof import("/tmp/tmp.9J6Axa8KMt/node_modules/@grpc/grpc-js/build/src/index")': makeClientConstructor, ChannelCredentials, CallCredentials, InterceptorConfigurationError, experimental

4 new PubSub({grpc});
              ~~~~

  node_modules/google-gax/build/src/grpc.d.ts:25:5
    25     grpc?: GrpcModule;
           ~~~~
    The expected type comes from property 'grpc' which is declared here on type 'ClientConfig'


Found 1 error.
```

**Comment by feywind** [comment] 2021-04-23 17:00
Thanks for the report! I suspect you can work around this by using `grpc as any`, but that's sort of gross. It looks like that `grpc.ts` file hasn't changed recently, so maybe @murgatroid99 would have insight on the type mismatch at the grpc level?

**Comment by murgatroid99** [comment] 2021-04-23 17:37
It looks like this is a result of additions to the types in the `@grpc/grpc-js` library that weren't reflected in the `grpc` library. And especially with the addition of the `experimental` namespace in grpc-js, it's unlikely that they're ever going to match again.

**Comment by feywind** [comment] 2021-04-23 17:38
It might be easiest to just recommend using the `grpc as any` workaround then, though I'm guessing some will have linter rules preventing that.

**Comment by mgabeler-lee-6rs** [comment] 2021-04-23 18:08
> I suspect you can work around this by using `grpc as any`, but that's sort of gross.

Indeed that is exactly what I did and why I filed this :slightly_smiling_face:

Despite the type checking errors, it seems to actually work fine, as expected. It just makes `tsc` and my linter angry.

> it's unlikely that they're ever going to match again

The way I've dealt with similar issues in my own projects where I want better type safety than `as any` is to have the receiving code declare the parameter it wants as something like `Pick<BigType, 'method1' | 'method2'>`. I think `Partial<BigType>` might also work as a way of getting `tsc` to check "these should look something like each other even if they aren't exactly the same", depending on how deep the types go.

The specific issue of `experimental` could be dealt with using `Omit<typeof grpc, 'experimental'>` I think?

**Comment by feywind** [comment] 2021-04-23 18:13
I should probably also tag in @alexander-fenster since gax is what's requesting the specific type.

**Comment by murgatroid99** [comment] 2021-04-23 18:34
`Pick` and `Partial` should both work, because all of the types that both libraries have should be compatible, and the issue is members that `@grpc/grpc-js` has and `grpc` doesn't have. `Omit` would probably be fragile because it would have to track all of those incompatibilities, which may change over time.

**Comment by feywind** [comment] 2021-11-02 16:40
Rather than leaving this hanging around, I am going to go ahead and close it, because:

* Things are moving on to grpc-js, and gRPC native is legacy, so there's not a big interest in bringing it up to date with this sort of thing
* There is a workaround that works
* The docs in the README.md are about JavaScript

I could see adding a blurb about `as any` to the README.md, but for end users, we are mostly focused on JavaScript, and TS folks probably know to throw it on there.

That might end up changing later, because e.g. I'm piloting adding TypeScript sample snippets, and there's some interest in making that a more widespread thing.

**Closed by feywind** 2021-11-02 16:40 UTC
Labels: priority: p2, type: bug, api: pubsub
